
import java.awt.HeadlessException;
import java.awt.Toolkit;

import java.sql.*;
import javax.swing.*;


public class Appointment_hm extends javax.swing.JFrame {

    /*Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;*/
    public Appointment_hm() {
        initComponents();
        setIcon();
        //conn=javaconnect.ConnectDB();
        Appoint_Table tb=new Appoint_Table();
                tb.Update_Appo();
                 check();
                //jButton2.setEnabled(false);
                //jButton8.setEnabled(false);
          
        
        
        
        
    }
     public void setIcon()
    {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo-nonetext.png")));
    }
      private void check()
    {
        Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    conn=javaconnect.ConnectDB();
        try
        {
            //b_nom.getText();
            String a="AP-3000";
            // b_nom.setText("MH-3000");
          //  String check= b_nom.getText();
            for(int i=0;i<1000;i++)
            {
            String sql="select Patient_ID from Appointment_table where Patient_ID>'"+a+"'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next())
            {
               
               a=rs.getString("Patient_ID");
              
            }
        }
            //b_nom.setText(a);
            String value=a;
            String va2=value.replaceAll("AP-", "");
            int VALUE=Integer.parseInt(va2);
            ++VALUE;
             appo_patient_id.setText("AP-"+VALUE);
            /*
             String VALUE    ="MH-1001";
        String v2=VALUE.replaceAll("MH-", "");
        int value=Integer.parseInt(v2);
        ++value;
        JOptionPane.showMessageDialog(null, "my replace code is\n\t\t\tMH-"+value);
            */
                    
                    
                    
            
            
            
        }
        catch(NumberFormatException | SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex+"\nConnection error\n\tplease check out");
        }
        finally
        {
            try
            {
              if(rs!=null)
              {
                  rs.close();
                  
              }
              if(pst!=null)
              {
                  pst.close();
              }
              if(conn!=null)
              {
                  conn.close();
              }
            }
            catch(SQLException ex)
            {
               JOptionPane.showMessageDialog(null, ex);
            }
        }
    }
     
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        appo_btn_search = new javax.swing.JButton();
        appo_search = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        appo_first_name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        appo_last_name = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        app_address = new javax.swing.JTextField();
        appo_contact = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        appo_appoint = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        appo_time = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        appo_patient_id = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        appo_date = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        appo_doctor_id = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Patient Appointment");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 190, 170);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Patient Appointment");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(190, 20, 560, 170);

        appo_btn_search.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        appo_btn_search.setForeground(new java.awt.Color(0, 102, 102));
        appo_btn_search.setText("Search");
        appo_btn_search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        appo_btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appo_btn_searchActionPerformed(evt);
            }
        });
        jPanel1.add(appo_btn_search);
        appo_btn_search.setBounds(1100, 30, 120, 40);

        appo_search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        appo_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                appo_searchKeyReleased(evt);
            }
        });
        jPanel1.add(appo_search);
        appo_search.setBounds(930, 30, 150, 35);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 102));
        jLabel17.setText("Patient ID");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(790, 30, 110, 40);

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton11.setForeground(new java.awt.Color(0, 102, 102));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home-icon (1).png"))); // NOI18N
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11);
        jButton11.setBounds(1280, 20, 60, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hospital-Top-Slider-Image.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(170, 20, 1200, 160);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Book an Appointment", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 36), new java.awt.Color(0, 51, 51))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("First Name");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 72, 148, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Last Name");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 180, 425, 35));

        appo_first_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(appo_first_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 128, 425, 34));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Address");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 294, 425, 31));

        appo_last_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(appo_last_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 239, 425, 34));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Contact");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 406, 425, 31));

        app_address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(app_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 345, 425, 34));

        appo_contact.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(appo_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 465, 425, 34));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Doctor Appointment");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 72, 199, 30));

        appo_appoint.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(appo_appoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 128, 149, 34));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("Set Date");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 180, 179, 35));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("Set Time");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 291, 161, 36));

        appo_time.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(appo_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 348, 147, 34));
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(955, 72, 131, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setText("Doctor ID");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(787, 72, 162, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("Patient ID");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(787, 180, 299, 35));

        appo_patient_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        appo_patient_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                appo_patient_idKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                appo_patient_idKeyTyped(evt);
            }
        });
        jPanel2.add(appo_patient_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(787, 239, 159, 33));

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 102, 102));
        jButton9.setText("Refresh");
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 462, 108, 36));

        appo_date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(appo_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 239, 161, 34));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 102));
        jButton2.setText("Save");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(787, 346, 117, 34));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 102, 102));
        jButton7.setText("DELETE");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(787, 403, 117, 37));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 102, 102));
        jButton8.setText("UPDATE");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(787, 465, 117, 33));

        appo_doctor_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        appo_doctor_id.setForeground(new java.awt.Color(0, 102, 102));
        appo_doctor_id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----none---", "DR-DS-001", "DR-SB-002", "DR-VB-003", "DR-PK-004" }));
        jPanel2.add(appo_doctor_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 128, 150, 34));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Staff", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(0, 102, 102))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staff_details.png"))); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("Staff Details");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staff add.png"))); // NOI18N

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 102));
        jButton3.setText("Add Staff");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/remove_staff.png"))); // NOI18N

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 102, 102));
        jButton4.setText("Remove Staff");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Patient Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 102, 102));
        jButton5.setText("Patient Details");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 42, 189, 40));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 102, 102));
        jButton6.setText("Payment / Check");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 105, -1, 40));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Actions-view-list-details-icon.png"))); // NOI18N
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, 40));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payment-icon.png"))); // NOI18N
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 50, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 988, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1370, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void appo_btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appo_btn_searchActionPerformed
        // TODO add your handling code here:
        Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    conn=javaconnect.ConnectDB();
        String sql="select * from Appointment_table where Patient_ID=?";
        try
        {
            String st=appo_search.getText();
            if(st.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Search Field is Empty");
            }
            else
            {
            pst=conn.prepareStatement(sql);
            pst.setString(1,appo_search.getText());
            rs=pst.executeQuery();
            if(rs.next())
            {
                String a=rs.getString("Patient_ID");
                appo_patient_id.setText(a);
                String b=rs.getString("First_Name");
                appo_first_name.setText(b);
                String c=rs.getString("Last_Name");
                appo_last_name.setText(c);
                String d=rs.getString("Address");
                app_address.setText(d);
                String e=rs.getString("Contact");  
                appo_contact.setText(e);
                String f=rs.getString("Contact");
                appo_appoint.setText(f);
                String g=rs.getString("Doctor_Appoint");
               appo_doctor_id.setSelectedItem(g);
                String h=rs.getString("Set_Date");
                ((JTextField)appo_date.getDateEditor().getUiComponent()).setText(h);
                String i=rs.getString("Set_Time");
                appo_time.setText(i);
                
              

                        

            }
            }
        }
        
        catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,"Error occured\t"+"\tyou can't update!  "+e );
            
            
                    
        }
       /* finally
        {
            try
            {
                rs.close();
                pst.close();
               conn.close();
                
            }
            catch(SQLException e)
            {
                
            }
        }*/
        finally
        {
            try
            {
              if(rs!=null)
              {
                  rs.close();
                  
              }
              if(pst!=null)
              {
                  pst.close();
              }
              if(conn!=null)
              {
                  conn.close();
              }
            }
            catch(SQLException e)
            {
               JOptionPane.showMessageDialog(null, e);
            }
        }
        
        //appo_btn_search.setEnabled(false);
    }//GEN-LAST:event_appo_btn_searchActionPerformed

    private void appo_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_appo_searchKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_appo_searchKeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Appoint_Table().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void appo_patient_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_appo_patient_idKeyReleased
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_appo_patient_idKeyReleased

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        dispose();
        //close();
        new Origine().setVisible(true);
        
        
        
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Payment().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        appo_first_name.setText("");
        appo_last_name.setText("");
        app_address.setText("");
        appo_contact.setText("");
        appo_appoint.setText("");
                        ((JTextField)appo_date.getDateEditor().getUiComponent()).setText("");
        appo_time.setText("");
        appo_doctor_id.setSelectedIndex(0);
        check();
        

        
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        Staff_hm s=new Staff_hm();
        s.setVisible(true);
        s.update_staff.setEnabled(false);
        s.add_Staff.setEnabled(false);
        s.delete_staff.setEnabled(false);
        //s.Staff_Update();
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
         Staff_hm j=new Staff_hm();
        j.setVisible(true);
        // j.Staff_Update();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
        Staff_hm j=new Staff_hm();
        j.setVisible(true);
        j.update_staff.setEnabled(false);
        j.add_Staff.setEnabled(false);
        
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    conn=javaconnect.ConnectDB();
        try
        {
            String st=appo_patient_id.getText();
            String ss=appo_doctor_id.getSelectedItem().toString();
            String sp=appo_first_name.getText();
            String stt=appo_last_name.getText();
            if(st.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Patient_ID is Empty");
            }
            else if(ss.isEmpty())
            {
                JOptionPane.showMessageDialog(null,"Please Enter Doctor ID first");
            }
            else if(sp.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Please enter Patient Name");
            }
            else if(stt.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Please enter Patient Name");
            }
            else
            {
            String sql="insert into Appointment_table (Patient_ID,First_Name,Last_Name,Address,Contact,Doctor_Appoint,Doctor_ID,Set_Date,Set_Time) values(?,?,?,?,?,?,?,?,?)";
            pst=conn.prepareStatement(sql);
            pst.setString(1,appo_patient_id.getText());
            pst.setString(2,appo_first_name.getText()); 
            pst.setString(3,appo_last_name.getText());
            pst.setString(4,app_address.getText());
            pst.setString(5,appo_contact.getText());
            pst.setString(6,appo_appoint.getText());
            pst.setString(7,appo_doctor_id.getSelectedItem().toString());
            pst.setString(8,((JTextField)appo_date.getDateEditor().getUiComponent()).getText());
            pst.setString(9,appo_time.getText());
            int p=JOptionPane.showConfirmDialog(null,"Do you want to save","Conform Save",JOptionPane.YES_NO_OPTION);
             if(p==0)
             { 
              pst.execute();
             JOptionPane.showMessageDialog(null, "Saved");  
             appo_first_name.setText("");
        appo_last_name.setText("");
        app_address.setText("");
        appo_contact.setText(""); 
        appo_appoint.setText("");
                        ((JTextField)appo_date.getDateEditor().getUiComponent()).setText("");
        appo_time.setText("");
        appo_doctor_id.setSelectedIndex(0);
      
                String VALUE=appo_patient_id.getText();
             String v2=VALUE.replaceAll("AP-", "");
        int value=Integer.parseInt(v2);
        ++value;
          appo_patient_id.setText("AP-"+value);
             }
            } 
            
        }
        catch(HeadlessException | NumberFormatException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, "Exception in inserting "+e);
        }
        
         finally
        {
            try
            {
              if(rs!=null)
              {
                  rs.close();
                  
              }
              if(pst!=null)
              {
                  pst.close();
              }
              if(conn!=null)
              {
                  conn.close();
              }
            }
            catch(SQLException e)
            {
               JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    conn=javaconnect.ConnectDB();
        try
        {
            String st=appo_search.getText();
            String st2=appo_patient_id.getText();
            if(st.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Search Field is Empty");
            }
            else if(st2.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Patient ID is Empty");
            }
            else
            {
                String V=appo_search.getText();
            String sql="delete from Appointment_table where Patient_ID='"+V+"'";
            pst=conn.prepareStatement(sql);
           
            pst.execute();
            
            JOptionPane.showMessageDialog(null,"Deleted");
            }
            appo_first_name.setText("");
        appo_last_name.setText("");
        app_address.setText("");
        appo_contact.setText("");
        appo_appoint.setText("");
                        ((JTextField)appo_date.getDateEditor().getUiComponent()).setText("");
        appo_time.setText("");
        appo_doctor_id.setSelectedIndex(0);
        appo_patient_id.setText("");
        }
        catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, "Deleted Exception "+e);
        }
        finally
        {
            try
            {
              if(rs!=null)
              {
                  rs.close();
                  
              }
              if(pst!=null)
              {
                  pst.close();
              }
              if(conn!=null)
              {
                  conn.close();
              }
            }
            catch(SQLException ex)
            {
               JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        /*
        UPDATE HERE
        */
         String a=appo_first_name.getText();
        String b=appo_last_name.getText();
        String c=app_address.getText();
       String d= appo_contact.getText();
        String e=appo_appoint.getText();
          String f=((JTextField)appo_date.getDateEditor().getUiComponent()).getText();
        String g=appo_time.getText();
        String h=appo_doctor_id.getSelectedItem().toString();
        String i=appo_patient_id.getText();
        Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    conn=javaconnect.ConnectDB();
        try
        {
            String st=appo_search.getText();
         
            if(st.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Search Field is Empty");
            }
            else if(i.isEmpty())
            {
                JOptionPane.showConfirmDialog(null, "Patient ID is Empty");
            }
            else
            {
            
            String sql="update  Appointment_table set First_Name='"+a+"',Last_Name='"+b+"',Address='"+c+"',Contact='"+d+"',Doctor_Appoint='"+e+"',Doctor_ID='"+h+"',Set_Date='"+f+"',Set_Time='"+g+"' where Patient_ID='"+i+"'";
             pst=conn.prepareStatement(sql);
            pst.execute();
            
                 JOptionPane.showMessageDialog(null,"UPDATED");
                 appo_first_name.setText("");
        appo_last_name.setText("");
        app_address.setText("");
        appo_contact.setText("");
        appo_appoint.setText("");
        ((JTextField)appo_date.getDateEditor().getUiComponent()).setText(""); 
        appo_time.setText("");
        appo_doctor_id.setSelectedIndex(0);
        appo_patient_id.setText("");
         Appoint_Table tb=new Appoint_Table();
                tb.Update_Appo();
            }
         
        
            
        }
        catch(HeadlessException | SQLException ex)
        {
            JOptionPane.showMessageDialog(null, e+"\nConnection Error\nplease check..");
        }
        finally
        {
            try
            {
              if(rs!=null)
              {
                  rs.close();
                  
              }
              if(pst!=null)
              {
                  pst.close();
              }
              if(conn!=null)
              {
                  conn.close();
              }
            }
            catch(SQLException ex)
            {
               JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void appo_patient_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_appo_patient_idKeyTyped
        // TODO add your handling code here:
        
        if(appo_patient_id.getText().equals("")) {
    jButton2.setEnabled(false);
    jButton8.setEnabled(false);
}
else {
    jButton2.setEnabled(true);
    jButton8.setEnabled(true);
}
    }//GEN-LAST:event_appo_patient_idKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Appointment_hm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Appointment_hm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Appointment_hm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Appointment_hm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                           new Appointment_hm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField app_address;
    private javax.swing.JTextField appo_appoint;
    private javax.swing.JButton appo_btn_search;
    private javax.swing.JTextField appo_contact;
    private com.toedter.calendar.JDateChooser appo_date;
    private javax.swing.JComboBox<String> appo_doctor_id;
    private javax.swing.JTextField appo_first_name;
    private javax.swing.JTextField appo_last_name;
    private javax.swing.JTextField appo_patient_id;
    private javax.swing.JTextField appo_search;
    private javax.swing.JTextField appo_time;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
