
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Doctor_info extends javax.swing.JFrame {
      String filename=null;
    byte[] person_image=null;
   /* Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;

*/
    /**
     * Creates new form Doctor_info
     */
    public Doctor_info() {
        initComponents();
        setIcon();
       // conn=javaconnect.ConnectDB();
        Show_Update();
         
        
    }
    public void setIcon()
    {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo-nonetext.png")));
    }
    public void Show_Update()
    {
        Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
     conn=javaconnect.ConnectDB();
         try
        {
            String sql="select Name,Mobile,Home,Visability,Visiting_From from Doctor_Man";

            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            d_info_table.setModel(DbUtils.resultSetToTableModel(rs));
           // rs=pst.executeQuery();

        }
         catch(SQLException e)
         {
             JOptionPane.showMessageDialog(null,e+"\nConnection Error\nplease check..");
         }
         finally
        {
            try
            {
              if(rs!=null)
              {
                  rs.close();
                  
              }
              if(pst!=null)
              {
                  pst.close();
              }
              if(conn!=null)
              {
                  conn.close();
              }
            }
            catch(SQLException ex)
            {
               JOptionPane.showMessageDialog(null, ex);
            }
        }
    }
  /*  public void show()
    {
        try
        {
            String sql="select Name,Mobile,Visability,Visiting_From from Doctor_Man";

            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            d_info_table.setModel(DbUtils.resultSetToTableModel(rs));
           // rs=pst.executeQuery();

        }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(null,e);
         }
         finally
         {
             try
             {
                 rs.close();
                 pst.close();
                 //conn.close();
             }
             catch(Exception e)
             {
                 
             }
         }
        
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jDesktopPane5 = new javax.swing.JDesktopPane();
        image_lable = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        d_txt_info = new javax.swing.JTextField();
        d_txt_name = new javax.swing.JTextField();
        d_txt_mobile = new javax.swing.JTextField();
        d_txt_home = new javax.swing.JTextField();
        d_txt_work = new javax.swing.JTextField();
        d_txt_email = new javax.swing.JTextField();
        d_txt_address = new javax.swing.JTextField();
        d_txt_doctor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        doctor_upload = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        d_txt_info1 = new javax.swing.JTextField();
        d_txt_info2 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        d_info_table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hospital Doctors");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 190, 170);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 102, 102));
        jButton4.setText("<< Back");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(1230, 30, 120, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Doctor Info");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(210, 50, 380, 120);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hospital-Top-Slider-Image.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(170, 20, 1200, 170);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Doctors", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 36), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane5.add(image_lable);
        image_lable.setBounds(10, 10, 120, 140);

        jPanel3.add(jDesktopPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 140, 160));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Visiting From");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 120, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Name");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 60, 120, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Mobile");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 100, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Home");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 120, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Work");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 120, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Email");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 120, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("Address");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 120, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("Doctor");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 120, 30));

        d_txt_info.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(d_txt_info, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 240, 30));

        d_txt_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(d_txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 240, 30));

        d_txt_mobile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(d_txt_mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 240, 30));

        d_txt_home.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(d_txt_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 240, 30));

        d_txt_work.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(d_txt_work, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 240, 30));

        d_txt_email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(d_txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 240, 30));

        d_txt_address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(d_txt_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 240, 30));

        d_txt_doctor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(d_txt_doctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 240, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("Refresh");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 570, 120, 40));

        doctor_upload.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        doctor_upload.setForeground(new java.awt.Color(0, 102, 102));
        doctor_upload.setText("Upload");
        doctor_upload.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        doctor_upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctor_uploadActionPerformed(evt);
            }
        });
        jPanel3.add(doctor_upload, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, 120, 40));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 102));
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 500, 120, 40));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 102, 102));
        jButton5.setText("Save");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 500, 120, 40));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 102, 102));
        jButton6.setText("Update");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 570, 120, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setText("Info");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 120, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("Visability");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 120, 30));

        d_txt_info1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(d_txt_info1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 600, 240, 30));

        d_txt_info2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(d_txt_info2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, 240, 30));

        jScrollPane1.setViewportView(jPanel3);

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Doctor Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 36), new java.awt.Color(0, 102, 102))); // NOI18N

        d_info_table.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        d_info_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        d_info_table.setRowHeight(30);
        d_info_table.setRowMargin(2);
        d_info_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                d_info_tableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(d_info_table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
     conn=javaconnect.ConnectDB();
        try
        {
            String st=d_txt_name.getText();
            if(st.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Doctor Name is Empty");
            }
            else
            {
            String sql="insert into Doctor_Man values(?,?,?,?,?,?,?,?,?,?,?)";
            pst=conn.prepareStatement(sql);
              pst.setString(1,d_txt_name.getText());
              pst.setString(2, d_txt_mobile.getText());
              pst.setString(3, d_txt_home.getText());
              pst.setString(4, d_txt_work.getText());
              pst.setString(5, d_txt_email.getText());
              pst.setString(6, d_txt_address.getText());
              pst.setString(7, d_txt_doctor.getText());
              pst.setString(8, d_txt_info.getText());
              pst.setBytes(9,person_image);
              pst.setString(10,d_txt_info2.getText());
              pst.setString(11, d_txt_info1.getText());
               int p=JOptionPane.showConfirmDialog(null,"Do you want to save","Conform Save",JOptionPane.YES_NO_OPTION);
             if(p==0)
             {
              pst.execute();
             JOptionPane.showMessageDialog(null, "Saved");
             Show_Update();
             d_txt_name.setText("");
             d_txt_mobile.setText("");
             d_txt_home.setText("");
             d_txt_work.setText("");
             d_txt_email.setText("");
             d_txt_address.setText("");
             d_txt_doctor.setText("");
             d_txt_info.setText("");
              image_lable.setIcon(null);
            image_lable.revalidate();
             }
            }
           
        }
        catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, e+"\nConnection Error\nplease check..");
            
        }
        finally
        {
            try
            {
              if(rs!=null)
              {
                  rs.close();
                  
              }
              if(pst!=null)
              {
                  pst.close();
              }
              if(conn!=null)
              {
                  conn.close();
              }
            }
            catch(SQLException ex)
            {
               JOptionPane.showMessageDialog(null, ex);
            }
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void doctor_uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctor_uploadActionPerformed
        // TODO add your handling code here:
         JFileChooser chooser=new JFileChooser();
      chooser.showOpenDialog(null);
      File f=chooser.getSelectedFile();
      filename=f.getAbsolutePath();
      ImageIcon imageicon=new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(image_lable.getWidth(), image_lable.getHeight(), Image.SCALE_SMOOTH));
      image_lable.setIcon(imageicon);
      try
      {
          File image=new File(filename);
          FileInputStream fis=new FileInputStream(image);
          ByteArrayOutputStream bos=new ByteArrayOutputStream();
          byte[] buf=new byte[1024];
          for(int readnum;(readnum=fis.read(buf))!=-1;)
          {
           bos.write(buf,0,readnum);    
          }
          person_image=bos.toByteArray();
          
      }
      catch(IOException e)
      {
          JOptionPane.showMessageDialog(null, "Some error occured Choose Image From File "+e);
      }
    }//GEN-LAST:event_doctor_uploadActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
     conn=javaconnect.ConnectDB();
        try
        {
            String st=d_txt_name.getText();
            if(st.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Doctor Name is Empty");
            }
            else
            {
                
            
            String sql="delete from Doctor_Man where Name=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1, d_txt_name.getText());
             int p=JOptionPane.showConfirmDialog(null,"Do you want to Delete","Conform Delete",JOptionPane.YES_NO_OPTION);
             if(p==0)
             {
              pst.execute();
             JOptionPane.showMessageDialog(null, "Deleted"); 
             Show_Update();
             }
            }
        }
        catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, e+"\nConnection Error\nplease check..");
        }
       finally
        {
            try
            {
              if(rs!=null)
              {
                  rs.close();
                  
              }
              if(pst!=null)
              {
                  pst.close();
              }
              if(conn!=null)
              {
                  conn.close();
              }
            }
            catch(SQLException ex)
            {
               JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
     conn=javaconnect.ConnectDB();
        try
        {
            String a=d_txt_name.getText();
            String b=d_txt_mobile.getText();
            String c=d_txt_home.getText();
            String d=d_txt_work.getText();
            String e=d_txt_email.getText();
            String f=d_txt_address.getText();
            String g=d_txt_doctor.getText();
            String h=d_txt_info.getText();
            String j=d_txt_info2.getText();
            String k=d_txt_info1.getText();
            if(a.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Doctor Name is Empty");
            }
            else
            { 
                
            
         String sql="update Doctor_Man set Mobile='"+b+"',Home='"+c+"',Work='"+d+"',Email='"+e+"',Address='"+f+"',Doctors='"+g+"',Info='"+h+"',Visability='"+j+"',Visiting_From='"+k+"' where Name='"+a+"'";
         
             pst=conn.prepareStatement(sql);
             int C=JOptionPane.showConfirmDialog(null,"Do you want to Really Save?","Conform Save",JOptionPane.YES_NO_OPTION);
              if(C==0)
              {
                   pst.execute();
                   JOptionPane.showMessageDialog(null, "Update Successfully");
              }
            }
            
              d_txt_name.setText("");
             d_txt_mobile.setText("");
             d_txt_home.setText("");
             d_txt_work.setText("");
             d_txt_email.setText("");
             d_txt_address.setText("");
             d_txt_doctor.setText("");
             d_txt_info.setText("");
             d_txt_info2.setText("");
             d_txt_info1.setText("");
              image_lable.setIcon(null);
            image_lable.revalidate();
            
        }
        catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, e+"\nConnection Error\nplease check..");
        }
        finally
        {
            try
            {
              if(rs!=null)
              {
                  rs.close();
                  
              }
              if(pst!=null)
              {
                  pst.close();
              }
              if(conn!=null)
              {
                  conn.close();
              }
            }
            catch(SQLException ex)
            {
               JOptionPane.showMessageDialog(null, ex);
            }
        }
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void d_info_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d_info_tableMouseClicked
        // TODO add your handling code here:
        doctor_upload.setEnabled(false);
        Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
     conn=javaconnect.ConnectDB();
        try
        {
            int row=d_info_table.getSelectedRow();
            String Table_click=(d_info_table.getModel().getValueAt(row,0).toString());
            String sqll="select * from Doctor_Man where Name='"+Table_click+"'";
            pst=conn.prepareStatement(sqll);
            rs=pst.executeQuery();
            if(rs.next())
            {
                String a=rs.getString("Name");
                d_txt_name.setText(a); 
                String b=rs.getString("Mobile");
                d_txt_mobile.setText(b);
                String c=rs.getString("Home");
                d_txt_home.setText(c);
                String d=rs.getString("Work");
                d_txt_work.setText(d);
                String e=rs.getString("Email");
                d_txt_email.setText(e);
                String f=rs.getString("Address");
                d_txt_address.setText(f);
                String g=rs.getString("Doctors");
                d_txt_doctor.setText(g);
                 byte[] bi=rs.getBytes("Imagess");
                ImageIcon image=new ImageIcon(bi);
                Image mi=image.getImage();
                Image myimg=mi.getScaledInstance(image_lable.getWidth(),image_lable.getHeight(),Image.SCALE_SMOOTH);
                ImageIcon newIcon=new ImageIcon(myimg);
                image_lable.setIcon(newIcon);
            image_lable.revalidate();
            String z=rs.getString("Info");
            d_txt_info.setText(z);
            String r=rs.getString("Visability");
            d_txt_info2.setText(r);
            String s=rs.getString("Visiting_From");
            d_txt_info1.setText(s);
            Show_Update();
            doctor_upload.setEnabled(false);
                /*
                
                */
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e+"\nConnection Error\nplease check..");
        }
       finally
        {
            try
            {
              if(rs!=null)
              {
                  rs.close();
                  
              }
              if(pst!=null)
              {
                  pst.close();
              }
              if(conn!=null)
              {
                  conn.close();
              }
            }
            catch(SQLException ex)
            {
               JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_d_info_tableMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
        new IN_patient().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        d_txt_name.setText("");
             d_txt_mobile.setText("");
             d_txt_home.setText("");
             d_txt_work.setText("");
             d_txt_email.setText("");
             d_txt_address.setText("");
             d_txt_doctor.setText("");
             d_txt_info.setText("");
              image_lable.setIcon(null);
            image_lable.revalidate();
            doctor_upload.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctor_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctor_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctor_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctor_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctor_info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable d_info_table;
    private javax.swing.JTextField d_txt_address;
    private javax.swing.JTextField d_txt_doctor;
    private javax.swing.JTextField d_txt_email;
    private javax.swing.JTextField d_txt_home;
    private javax.swing.JTextField d_txt_info;
    private javax.swing.JTextField d_txt_info1;
    private javax.swing.JTextField d_txt_info2;
    private javax.swing.JTextField d_txt_mobile;
    private javax.swing.JTextField d_txt_name;
    private javax.swing.JTextField d_txt_work;
    private javax.swing.JButton doctor_upload;
    private javax.swing.JLabel image_lable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JDesktopPane jDesktopPane5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
