/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
import java.awt.Image;
import java.io.*;
import javax.swing.*;
import javax.swing.filechooser.*;
import java.sql.*;
import java.awt.*;

public class IN_patient extends javax.swing.JFrame {
    String filename=null;
    String filename1=null;
    byte[] person_image=null; 
    /*Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
*/
    /**
     * Creates new form IN_patient
     */
    public IN_patient() {
        initComponents();
        setIcon();
       // conn=javaconnect.ConnectDB();
         check();
    }
    public void setIcon()
    {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo-nonetext.png")));
    }
    public void check()
    {
        Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    conn=javaconnect.ConnectDB();
        try
        {
            //b_nom.getText();
            String a="IPD-3000";
            // b_nom.setText("MH-3000");
          //  String check= b_nom.getText();
            for(int i=0;i<1000;i++)
            {
            String sql="select Patient_ID from In_Patient where Patient_ID>'"+a+"'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next())
            {
               
               a=rs.getString("Patient_ID");
              
            }
        }
            //b_nom.setText(a);
            String value=a;
            String va2=value.replaceAll("IPD-", "");
            int VALUE=Integer.parseInt(va2);
            ++VALUE;
             in_patient_id.setText("IPD-"+VALUE);
            /*
             String VALUE    ="MH-1001";
        String v2=VALUE.replaceAll("MH-", "");
        int value=Integer.parseInt(v2);
        ++value;
        JOptionPane.showMessageDialog(null, "my replace code is\n\t\t\tMH-"+value);
            */
                    
                    
                    
            
            
            
        }
        catch(NumberFormatException | SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex+"\nConnection error\n\tplease check out");
        }
        finally
        {
            try
            {
              if(rs!=null)
              {
                  rs.close();
                  
              }
              if(pst!=null)
              {
                  pst.close();
              }
              if(conn!=null)
              {
                  conn.close();
              }
            }
            catch(SQLException ex)
            {
               JOptionPane.showMessageDialog(null, ex);
            }
        }
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        in_p_search = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        pi_images = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ip_dod = new com.toedter.calendar.JDateChooser();
        ip_dob = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        ip_doa = new com.toedter.calendar.JDateChooser();
        jLabel19 = new javax.swing.JLabel();
        ip_treatment = new javax.swing.JTextField();
        in_patient_first = new javax.swing.JTextField();
        ip_patient_last = new javax.swing.JTextField();
        ip_patient_gender = new javax.swing.JTextField();
        ip_weight = new javax.swing.JTextField();
        ip_age = new javax.swing.JTextField();
        in_patient_id = new javax.swing.JTextField();
        ip_mobile = new javax.swing.JTextField();
        ip_address = new javax.swing.JTextField();
        ip_room = new javax.swing.JTextField();
        ip_live_with = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        UP_IN = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admit Patient, Doctor Info");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 190, 170);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("IN Patient");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(190, 20, 560, 170);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Patient ID");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(800, 30, 120, 40);

        in_p_search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(in_p_search);
        in_p_search.setBounds(920, 30, 160, 40);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 102, 102));
        jButton4.setText("Search");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(1100, 30, 120, 40);

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton11.setForeground(new java.awt.Color(0, 102, 102));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home-icon (1).png"))); // NOI18N
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11);
        jButton11.setBounds(1280, 20, 60, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hospital-Top-Slider-Image.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(170, 20, 1200, 170);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "IN_Patinet_Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 36), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setLayer(pi_images, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pi_images, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pi_images, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 60, 130, 140));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Last Name");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 130, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Gender");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 90, 31));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Age");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 40, 31));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Weight");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 70, 31));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("D_O_B");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 70, 31));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("D_O_A");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 300, 114, 31));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("Guardians");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 120, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setText("Treatment By");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 480, -1, 27));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("Room no");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 420, 88, 31));

        ip_dod.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(ip_dod, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 170, 30));

        ip_dob.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(ip_dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 360, 190, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setText("D_O_D");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 360, 104, 31));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 102));
        jLabel15.setText("Mobile");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 117, 114, 31));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 102));
        jLabel16.setText("Address");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 183, 114, 31));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 102));
        jLabel17.setText("First Name");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 130, 31));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 102));
        jLabel18.setText("Patient ID");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 120, 31));

        ip_doa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(ip_doa, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 170, 31));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 102));
        jLabel19.setText("Photo");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, 60, 30));

        ip_treatment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(ip_treatment, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 480, 210, 29));

        in_patient_first.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(in_patient_first, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 190, 30));

        ip_patient_last.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(ip_patient_last, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 190, 30));

        ip_patient_gender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ip_patient_gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ip_patient_genderActionPerformed(evt);
            }
        });
        jPanel2.add(ip_patient_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 150, 30));

        ip_weight.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(ip_weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 190, 30));

        ip_age.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(ip_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 480, 170, 30));

        in_patient_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        in_patient_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_patient_idActionPerformed(evt);
            }
        });
        in_patient_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                in_patient_idKeyReleased(evt);
            }
        });
        jPanel2.add(in_patient_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 190, 29));

        ip_mobile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(ip_mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 149, 29));

        ip_address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(ip_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 210, 29));

        ip_room.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ip_room.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ip_roomActionPerformed(evt);
            }
        });
        jPanel2.add(ip_room, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 149, 29));

        ip_live_with.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(ip_live_with, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 149, 29));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("DELETE");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 470, 120, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 102));
        jButton2.setText("SAVE");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 350, 120, 40));

        UP_IN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        UP_IN.setForeground(new java.awt.Color(0, 102, 102));
        UP_IN.setText("UPLOAD");
        UP_IN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UP_IN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UP_INActionPerformed(evt);
            }
        });
        jPanel2.add(UP_IN, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 220, 130, 30));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 102, 102));
        jButton7.setText("UPDATE");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 410, 120, 40));

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton12.setForeground(new java.awt.Color(0, 102, 102));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button-Refresh-icon.png"))); // NOI18N
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 60, 60));

        jButton8.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 102, 102));
        jButton8.setText("Capture");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(815, 270, 100, 30));

        jScrollPane1.setViewportView(jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "In Patient Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 36), new java.awt.Color(0, 102, 102))); // NOI18N

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 102, 102));
        jButton5.setText("Patient Details");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 102, 102));
        jButton6.setText("Payment\\check");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Actions-view-list-details-icon.png"))); // NOI18N

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payment-icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(30, 30, 30))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Doctor Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 36), new java.awt.Color(0, 102, 102))); // NOI18N

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 102, 102));
        jButton9.setText("Avilable Doctors");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(0, 102, 102));
        jButton10.setText("Visited Doctors");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/People-Doctor-Male-icon (2).png"))); // NOI18N

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stethoscope-icon (2).png"))); // NOI18N

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor-icon (2).png"))); // NOI18N

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 102));
        jButton3.setText("Doctors");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jScrollPane2.setViewportView(jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 974, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ip_patient_genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ip_patient_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ip_patient_genderActionPerformed

    private void UP_INActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UP_INActionPerformed
        // TODO add your handling code here:
      JFileChooser chooser=new JFileChooser();
      
      chooser.showOpenDialog(null);
      FileNameExtensionFilter filter=new FileNameExtensionFilter("*.IMAGE","JPG","GIF","PNG");
      chooser.addChoosableFileFilter(filter);
      
      File f=chooser.getSelectedFile();
      
      filename=f.getAbsolutePath();
    
      /*
      below from we want to use this code line into our hospital_bill.java jFrame program
      */
      ImageIcon imageicon=new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(pi_images.getWidth(), pi_images.getHeight(), Image.SCALE_SMOOTH));
      pi_images.setIcon(imageicon);
      try
      { 
          
          File image=new File(filename);
          System.out.println(filename);
         
          FileInputStream fis=new FileInputStream(image.getCanonicalPath());
          ByteArrayOutputStream bos=new ByteArrayOutputStream();
          byte[] buf=new byte[1024];
          for(int readnum;(readnum=fis.read(buf))!=-1;)
          {
              
           bos.write(buf,0,readnum);    
          }
          person_image=bos.toByteArray();
          
      }
      catch(IOException e)
      {
          JOptionPane.showMessageDialog(null, "Some error occured  "+e);
      }
    }//GEN-LAST:event_UP_INActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    conn=javaconnect.ConnectDB();
        try
        {
            String st=in_patient_id.getText();
            if(st.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Patient ID is Empty");
            }
            else
            {
            String sql="insert into In_Patient (Patient_ID,First_Name,Last_Name,Gender,Age,Weight,DOB,Mobile,Address,Live_with,DOA,DOD,Room_no,Treatment_By,Images) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            pst=conn.prepareStatement(sql); 
            pst.setString(1,in_patient_id.getText());
            pst.setString(2,in_patient_first.getText());
            pst.setString(3,ip_patient_last.getText());
            pst.setString(4,ip_patient_gender.getText()); 
            pst.setString(5,ip_age.getText());
            pst.setString(6,ip_weight.getText());
            pst.setString(7,((JTextField)ip_dob.getDateEditor().getUiComponent()).getText());
            pst.setString(8,ip_mobile.getText());
            pst.setString(9,ip_address.getText());
            pst.setString(10,ip_live_with.getText());
            pst.setString(11,((JTextField)ip_doa.getDateEditor().getUiComponent()).getText());
            pst.setString(12,((JTextField)ip_dod.getDateEditor().getUiComponent()).getText());
            pst.setString(13,ip_room.getText());
            pst.setString(14,ip_treatment.getText());
            pst.setBytes(15,person_image);
            int p=JOptionPane.showConfirmDialog(null,"Do you want to save","Conform Save",JOptionPane.YES_NO_OPTION);
             if(p==0)
             {
              pst.execute();
             JOptionPane.showMessageDialog(null, "Saved");
            String VALUE=in_patient_id.getText();
             String v2=VALUE.replaceAll("IPD-", "");
        int value=Integer.parseInt(v2);
        ++value;
        in_patient_id.setText("IPD-"+value);
             in_patient_first.setText("");
             ip_patient_last.setText("");
             ip_patient_gender.setText("");
             ip_age.setText("");
             ip_weight.setText(""); 
             ((JTextField)ip_dod.getDateEditor().getUiComponent()).setText("");
              ((JTextField)ip_dob.getDateEditor().getUiComponent()).setText("");
             ip_mobile.setText("");
             ip_address.setText("");
             ip_live_with.setText("");
             ((JTextField)ip_doa.getDateEditor().getUiComponent()).setText("");
             ip_room.setText("");
             ip_treatment.setText("");
              pi_images.setIcon(null);
            pi_images.revalidate();
             }
            }
            
        }
        catch(HeadlessException | NumberFormatException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,e+"\nConnection Error\nplease check..");
        }
        finally
        {
            try
            {
              if(rs!=null)
              {
                  rs.close();
                  
              }
              if(pst!=null)
              {
                  pst.close();
              }
              if(conn!=null)
              {
                  conn.close();
              }
            }
            catch(SQLException ex)
            {
               JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    conn=javaconnect.ConnectDB();
        String serch=in_p_search.getText();
         String sql="select * from In_Patient where Patient_ID=?";
         try
        {
            if(serch.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Search Field is Empty");
            }
            else
            {
            pst=conn.prepareStatement(sql);
            pst.setString(1,in_p_search.getText());
            rs=pst.executeQuery();
            if(rs.next()) 
            {
               String a=rs.getString("Patient_ID");
               in_patient_id.setText(a);
                String b=rs.getString("First_Name");
               in_patient_first.setText(b);
                String c=rs.getString("Last_Name");
               ip_patient_last.setText(c);
                String d=rs.getString("Gender");
               ip_patient_gender.setText(d);
                String e=rs.getString("Age");
               ip_age.setText(e);
                String f=rs.getString("Weight");
               ip_weight.setText(f);
               String g=rs.getString("DOB");
               ((JTextField)ip_dob.getDateEditor().getUiComponent()).setText(g);
                String h=rs.getString("Mobile");
               ip_mobile.setText(h);
                String i=rs.getString("Address");
               ip_address.setText(i);
                String j=rs.getString("Live_with");
               ip_live_with.setText(j);
                String k=rs.getString("DOA");
                ((JTextField)ip_doa.getDateEditor().getUiComponent()).setText(k);
               
                String l=rs.getString("DOD");
            ((JTextField)ip_dod.getDateEditor().getUiComponent()).setText(l);
                String m=rs.getString("Room_no");
               ip_room.setText(m);
                String n=rs.getString("Treatment_By");
               ip_treatment.setText(n);
               byte[] bi=rs.getBytes("Images"); 
                ImageIcon image=new ImageIcon(bi);
                Image mi=image.getImage();
                Image myimg=mi.getScaledInstance(pi_images.getWidth(),pi_images.getHeight(),Image.SCALE_SMOOTH);
                ImageIcon newIcon=new ImageIcon(myimg);
                pi_images.setIcon(newIcon);
            pi_images.revalidate();
            UP_IN.setEnabled(false);
                         
               
               
            }  
            else
            {
                JOptionPane.showMessageDialog(null, "Sorry No result found");
            }
            }
        }
         catch(HeadlessException | SQLException e)
         {
             JOptionPane.showMessageDialog(null,e+"\n\t\tConnection Error\n\t\tplease check..");
         }
         finally
        {
            try
            {
              if(rs!=null)
              {
                  rs.close();
                  
              }
              if(pst!=null)
              {
                  pst.close();
              }
              if(conn!=null)
              {
                  conn.close();
              }
            }
            catch(SQLException ex)
            {
               JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Admitted().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        
        dispose();
        new Origine().setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String a=in_patient_id.getText();
        String b=in_patient_first.getText();
        String c=ip_patient_last.getText();
        String d=ip_patient_gender.getText();
        String e=ip_age.getText();
        String f=ip_weight.getText();
        String g=ip_mobile.getText();
         String h=((JTextField)ip_doa.getDateEditor().getUiComponent()).getText();
          String i=((JTextField)ip_dod.getDateEditor().getUiComponent()).getText();
        String j=ip_address.getText();
        String k=ip_live_with.getText();
        String l=ip_room.getText();
        String m=((JTextField)ip_dob.getDateEditor().getUiComponent()).getText();
        String n=ip_treatment.getText();
       
        Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    conn=javaconnect.ConnectDB();
        try
        {
              
           if(a.isEmpty())
           {
               JOptionPane.showMessageDialog(null, "Patient ID is Empty");
           }
           else
           {
            String sql="update In_Patient set First_Name='"+b+"',Last_Name='"+c+"',Gender='"+d+"',Age='"+e+"',Weight='"+f+"',DOB='"+m+"',Mobile='"+g+"',Address='"+j+"',Live_with='"+k+"',DOA='"+h+"',DOD='"+i+"',Room_no='"+l+"',Treatment_By='"+n+"' where Patient_ID='"+a+"'";
             pst=conn.prepareStatement(sql);
            pst.execute();
            
                 JOptionPane.showMessageDialog(null,"UPDATED");
           }
                 in_patient_id.setText("");
                in_patient_first.setText("");
                ip_patient_last.setText("");
                ip_patient_gender.setText("");
                ((JTextField)ip_dob.getDateEditor().getUiComponent()).setText("");
                ip_weight.setText("");
                ip_age.setText("");
                ip_mobile.setText("");
                ip_address.setText("");
                ip_live_with.setText("");
                ((JTextField)ip_doa.getDateEditor().getUiComponent()).setText("");
                ((JTextField)ip_dod.getDateEditor().getUiComponent()).setText("");
                ip_room.setText("");
                ip_treatment.setText("");
                pi_images.setIcon(null);
                pi_images.revalidate();

        }
        catch(HeadlessException | SQLException ex)
        {
            JOptionPane.showMessageDialog(null, e+"\nConnection Error\nplease check..");
        }
        finally
        {
            try
            {
              if(rs!=null)
              {
                  rs.close();
                  
              }
              if(pst!=null)
              {
                  pst.close();
              }
              if(conn!=null)
              {
                  conn.close();
              }
            }
            catch(SQLException ex)
            {
               JOptionPane.showMessageDialog(null, ex);
            }
        }

        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
       check();
                in_patient_first.setText("");
                ip_patient_last.setText("");
                ip_patient_gender.setText("");
                ((JTextField)ip_dob.getDateEditor().getUiComponent()).setText("");
                ip_weight.setText("");
                ip_age.setText("");
                ip_mobile.setText("");
                ip_address.setText("");
                ip_live_with.setText("");
                ((JTextField)ip_doa.getDateEditor().getUiComponent()).setText("");
                ((JTextField)ip_dod.getDateEditor().getUiComponent()).setText("");
                ip_room.setText("");
                ip_treatment.setText("");
                pi_images.setIcon(null);
                pi_images.revalidate();
                UP_IN.setEnabled(true);

        
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    conn=javaconnect.ConnectDB();
        try
        {
            
            String st=in_patient_id.getText();
            if(st.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Patient Id is Empty");
                
            }
            else
            {
                String ab=in_p_search.getText();
            String sql="delete from In_Patient where Patient_ID='"+ab+"'";
            pst=conn.prepareStatement(sql);
          //  pst.setString(1, in_patient_id.getText());

            int p=JOptionPane.showConfirmDialog(null,"Do you want to Delete","Conform Delete",JOptionPane.YES_NO_OPTION);
            if(p==0)
            {
                pst.execute();
                JOptionPane.showMessageDialog(null, "Deleted"); 
                in_patient_id.setText("");
                in_patient_first.setText("");
                ip_patient_last.setText("");
                ip_patient_gender.setText("");
                ((JTextField)ip_dob.getDateEditor().getUiComponent()).setText("");
                ip_weight.setText("");
                ip_age.setText("");
                ip_mobile.setText("");
                ip_address.setText("");
                ip_live_with.setText("");
                ((JTextField)ip_doa.getDateEditor().getUiComponent()).setText("");
                ((JTextField)ip_dod.getDateEditor().getUiComponent()).setText("");
                ip_room.setText("");
                ip_treatment.setText("");
                pi_images.setIcon(null);
                pi_images.revalidate();

            }
            }
        }
        catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,e+"\nConnection Error\nplease check..");
        }
        finally
        {
            try
            {
              if(rs!=null)
              {
                  rs.close();
                  
              }
              if(pst!=null)
              {
                  pst.close();
              }
              if(conn!=null)
              {
                  conn.close();
              }
            }
            catch(SQLException ex)
            {
               JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Payment_method().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void in_patient_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_in_patient_idKeyReleased
        // TODO add your handling code here:
        /*
        im.commming
        
        */
        if(in_patient_id.getText().equals("")) {
    UP_IN.setEnabled(false);
}else {
    UP_IN.setEnabled(true);
}
    }//GEN-LAST:event_in_patient_idKeyReleased

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
       dispose();
       new Doctor_info().setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Doctor_info().setVisible(true);
      
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Doctor_info().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ip_roomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ip_roomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ip_roomActionPerformed

    private void in_patient_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_patient_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_patient_idActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        
        new NewJFrame().setVisible(true);
        
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IN_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IN_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IN_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IN_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IN_patient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UP_IN;
    private javax.swing.JTextField in_p_search;
    private javax.swing.JTextField in_patient_first;
    private javax.swing.JTextField in_patient_id;
    private javax.swing.JTextField ip_address;
    private javax.swing.JTextField ip_age;
    private com.toedter.calendar.JDateChooser ip_doa;
    private com.toedter.calendar.JDateChooser ip_dob;
    private com.toedter.calendar.JDateChooser ip_dod;
    private javax.swing.JTextField ip_live_with;
    private javax.swing.JTextField ip_mobile;
    private javax.swing.JTextField ip_patient_gender;
    private javax.swing.JTextField ip_patient_last;
    private javax.swing.JTextField ip_room;
    private javax.swing.JTextField ip_treatment;
    private javax.swing.JTextField ip_weight;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel pi_images;
    // End of variables declaration//GEN-END:variables
}
