
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
import java.sql.*;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

public class Ordinary_Bill extends javax.swing.JFrame {
    /*Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
*/
    /**
     * Creates new form Ordinary_Bill
     */
    public Ordinary_Bill() {
        initComponents();
        setIcon();
        //conn=javaconnect.ConnectDB();
        check();
        Update_Bill();
        // jButton4.setEnabled(false);
    }
    public void setIcon()
    {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo-nonetext.png")));
    }
    public void check()
    {
        Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    conn=javaconnect.ConnectDB();
        try
        {
            //b_nom.getText();
            String a="OPDB-3000";
            // b_nom.setText("MH-3000");
          //  String check= b_nom.getText();
            for(int i=0;i<1000;i++)
            {
            String sql="select Bill_No from Oridinary_Bill where Bill_no>'"+a+"'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next())
            {
               
               a=rs.getString("Bill_No");
              
            }
        }
            //b_nom.setText(a);
            String value=a;
            String va2=value.replaceAll("OPDB-", "");
            int VALUE=Integer.parseInt(va2);
            ++VALUE;
             o_no.setText("OPDB-"+VALUE);
            /*
             String VALUE    ="MH-1001";
        String v2=VALUE.replaceAll("MH-", "");
        int value=Integer.parseInt(v2);
        ++value;
        JOptionPane.showMessageDialog(null, "my replace code is\n\t\t\tMH-"+value);
            */
                    
                    
                    
            
            
            
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex+"\nConnection error\n\tplease check out");
        }
        finally
        {
            try
            {
              if(rs!=null)
              {
                  rs.close();
                  
              }
              if(pst!=null)
              {
                  pst.close();
              }
              if(conn!=null)
              {
                  conn.close();
              }
            }
            catch(SQLException ex)
            {
               JOptionPane.showMessageDialog(null, ex);
            }
        }
    }
    public void Update_Bill()
    {
        Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    conn=javaconnect.ConnectDB();
         
        try
        {
         String sql="select Bill_No,First_Name,Last_Name,Address from Oridinary_Bill order by Bill_No";
            //String sql="select * from Billing order by Bill_No";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            table_bill.setModel(DbUtils.resultSetToTableModel(rs));
           // rs=pst.executeQuery();

        }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(null,"Exception 8 "+e);
         }
         finally
        {
            try
            {
              if(rs!=null)
              {
                  rs.close();
                  
              }
              if(pst!=null)
              {
                  pst.close();
              }
              if(conn!=null)
              {
                  conn.close();
              }
            }
            catch(SQLException ex)
            {
               JOptionPane.showMessageDialog(null, ex);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        o_id = new javax.swing.JTextField();
        o_no = new javax.swing.JTextField();
        o_first = new javax.swing.JTextField();
        o_last = new javax.swing.JTextField();
        o_address = new javax.swing.JTextField();
        o_check = new javax.swing.JTextField();
        o_injection = new javax.swing.JTextField();
        o_im = new javax.swing.JTextField();
        o_saline = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_bill = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ordinary Patient Bill");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 190, 170);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 102, 102));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home-icon (1).png"))); // NOI18N
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(1280, 20, 60, 60);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Ordinary Patient Bill");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(200, 40, 520, 100);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hospital-Top-Slider-Image.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(170, 20, 1200, 170);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ordinary Bill", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 36), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Patient ID");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 94, 130, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Bill No");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 157, 130, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("First Name");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 215, 130, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Last Name");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 273, 130, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Address");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 329, 130, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("CheckUp Charge");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 386, 160, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("Injection Charge");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 442, -1, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("I.M.Charge");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 505, 154, 30));

        o_id.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(o_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 97, 220, 30));

        o_no.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(o_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 157, 220, 30));

        o_first.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(o_first, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 218, 220, 30));

        o_last.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(o_last, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 276, 220, 30));

        o_address.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(o_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 332, 220, 30));

        o_check.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(o_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 389, 220, 30));

        o_injection.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(o_injection, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 445, 220, 30));

        o_im.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(o_im, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 505, 220, 30));

        o_saline.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(o_saline, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 562, 220, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("Save");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 110, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 102));
        jButton2.setText("Update");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 110, 40));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 102));
        jButton3.setText("Delete");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 473, 110, 40));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 102, 102));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button-Next-icon (1).png"))); // NOI18N
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 590, 70, 50));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setText("Saline Charge");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 559, 130, 30));

        total.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 610, 80, 30));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 102, 102));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add-1-icon.png"))); // NOI18N
        jButton6.setText("Total");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 610, 120, 30));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button-Refresh-icon.png"))); // NOI18N
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, 50, 50));

        jDateChooser1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 610, 150, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setText("Date");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 610, -1, 30));

        jScrollPane1.setViewportView(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bill Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 36), new java.awt.Color(0, 102, 102))); // NOI18N

        table_bill.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        table_bill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_bill.setRowHeight(25);
        table_bill.setRowMargin(2);
        table_bill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_billMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_bill);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        /*
        
        */
        Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    conn=javaconnect.ConnectDB();
        try
        {
            String st2=o_no.getText();
            String st=o_id.getText();
            if(st.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Patient id Empty");
            }
            else if(st2.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Bill No is Empty");
                
            }
            else
            {
            
             String sql="delete from Oridinary_Bill where Patient_ID=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1, o_id.getText());

            int p=JOptionPane.showConfirmDialog(null,"Do you want to Delete","Conform Delete",JOptionPane.YES_NO_OPTION);
            if(p==0)
            {
                pst.execute();
                JOptionPane.showMessageDialog(null, "Deleted");
                Update_Bill();
                
            }
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
         finally
        {
            try
            {
              if(rs!=null)
              {
                  rs.close();
                  
              }
              if(pst!=null)
              {
                  pst.close();
              }
              if(conn!=null)
              {
                  conn.close();
              }
            }
            catch(SQLException ex)
            {
               JOptionPane.showMessageDialog(null, ex);
            }
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void table_billMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_billMouseClicked
        // TODO add your handling code here:
        /*
        HERE WE PERFORM TABLE DISPLAY CODINNG///
        */
        Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    conn=javaconnect.ConnectDB();
        try
        {
            
            int row=table_bill.getSelectedRow();
            String Table_click=(table_bill.getModel().getValueAt(row,0).toString());
            String sql="select * from Oridinary_Bill where Bill_No='"+Table_click+"'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next())
            {
                String a=rs.getString("Patient_ID");
                o_id.setText(a);
                String b=rs.getString("Bill_No");
                o_no.setText(b);
                String c=rs.getString("First_Name");
                o_first.setText(c);
                String d=rs.getString("Last_Name");
                o_last.setText(d);
                String e=rs.getString("Address");
                o_address.setText(e);
                String f=rs.getString("CheckUp_fees");
                o_check.setText(f);
                String g=rs.getString("Injection_fees");
                o_injection.setText(g);
                String h=rs.getString("I_M_fees");
                o_im.setText(h);
                String j=rs.getString("Saline_fees");
                o_saline.setText(j);
                String k=rs.getString("Total");
                total.setText(k);
                String l=rs.getString("Date");
                ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).setText(l);
                
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
         finally
        {
            try
            {
              if(rs!=null)
              {
                  rs.close();
                  
              }
              if(pst!=null)
              {
                  pst.close();
              }
              if(conn!=null)
              {
                  conn.close();
              }
            }
            catch(SQLException ex)
            {
               JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_table_billMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    conn=javaconnect.ConnectDB();
        try
        {
            String st=o_id.getText();
            String st2=o_no.getText();
            if(st.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Patient ID is Empty");
            }
            else if(st2.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Bill No is Empty");
            }
            else
            {
            String sql="insert into Oridinary_Bill  values(?,?,?,?,?,?,?,?,?,?,?)";
            pst=conn.prepareStatement(sql);
            pst.setString(1,o_id.getText());
             pst.setString(2,o_no.getText());
              pst.setString(3,o_first.getText());
               pst.setString(4,o_last.getText());
                pst.setString(5,o_address.getText());
                 pst.setString(6,o_check.getText());
                  pst.setString(7,o_injection.getText());
                   pst.setString(8,o_im.getText());
                    pst.setString(9,o_saline.getText());
                   //  int c=Integer.parseInt(o_charge.getText());
             
             pst.setString(10, total.getText());
                        pst.setString(11,((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText());
                   
            int p=JOptionPane.showConfirmDialog(null,"Do you want to save","Conform Save",JOptionPane.YES_NO_OPTION);

             if(p==0)
             {
              pst.execute();
              Update_Bill();
              jButton4.setEnabled(true);
             JOptionPane.showMessageDialog(null, "Saved");
             }
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
         finally
        {
            try
            {
              if(rs!=null)
              {
                  rs.close();
                  
              }
              if(pst!=null)
              {
                  pst.close();
              }
              if(conn!=null)
              {
                  conn.close();
              }
            }
            catch(SQLException ex)
            {
               JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String ao=o_check.getText();
        String av=o_injection.getText();
        String ac=o_im.getText();
        String az=o_saline.getText();
        
        if(ao.isEmpty())
            {
            JOptionPane.showMessageDialog(null, "please fill bill amount");
        }
        else
            if(av.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "please fill bill amount");
            }
            else if(ac.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "please fill bill amount");
            }
            else if(az.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "please fill bill amount");
            }
        else
            {
         int d=Integer.parseInt(o_check.getText());
             int e=Integer.parseInt(o_injection.getText());
             int f=Integer.parseInt(o_im.getText());
             int g=Integer.parseInt(o_saline.getText());
             int add=(d+e+f+g);
             total.setText(String.valueOf(add));
             }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        /*
        
        
        */
        Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    conn=javaconnect.ConnectDB();
        String a=o_id.getText();
         String b=o_no.getText();
         String c=o_first.getText();
         String d=o_last.getText();
         String e=o_address.getText();
         String f=o_check.getText();
         String g=o_injection.getText();
         String h=o_im.getText();
         String i=o_saline.getText();
         String j=total.getText();
         String k=(((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText());
         try
         {
             if(a.isEmpty())
             {
                 JOptionPane.showMessageDialog(null, "Patient Id is Empty");
             }
             else if(b.isEmpty())
             {
                 JOptionPane.showMessageDialog(null, "Bill no is empty");
             }
             else
             {
                 
             
             String sql="update Oridinary_Bill set Bill_No='"+b+"',First_Name='"+c+"',Last_Name='"+d+"',Address='"+e+"',CheckUp_fees='"+f+"',Injection_fees='"+g+"',Date='"+k+"',I_M_fees='"+h+"',Saline_fees='"+i+"' where Patient_ID='"+a+"'";
            pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "UPDATED SUCCUSSFULLYU !!");
            Update_Bill();
             }
         }
         catch(Exception ex)
         {
             JOptionPane.showMessageDialog(null, ex);
         }
         finally
        {
            try
            {
              if(rs!=null)
              {
                  rs.close();
                  
              }
              if(pst!=null)
              {
                  pst.close();
              }
              if(conn!=null)
              {
                  conn.close();
              }
            }
            catch(SQLException ex)
            {
               JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        o_id.setText("");
                 check();

         o_first.setText("");
         o_last.setText("");
         o_address.setText("");
         o_check.setText("");
         o_injection.setText("");
         o_im.setText("");
         o_saline.setText("");
         total.setText("");
         ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).setText("");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
        String avs=o_id.getText();
        String ars=o_no.getText();
        Hospital_bill_Ordinary yes=new Hospital_bill_Ordinary(avs);
        yes.setVisible(true);
      //Ordinary_print print=new Ordinary_print();
       
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Origine().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ordinary_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ordinary_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ordinary_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ordinary_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ordinary_Bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField o_address;
    private javax.swing.JTextField o_check;
    private javax.swing.JTextField o_first;
    private javax.swing.JTextField o_id;
    private javax.swing.JTextField o_im;
    private javax.swing.JTextField o_injection;
    private javax.swing.JTextField o_last;
    private javax.swing.JTextField o_no;
    private javax.swing.JTextField o_saline;
    private javax.swing.JTable table_bill;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
