/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */ 

/**
 *
 * @author User
 */
import java.awt.*;
import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
public class Patients_Detail extends javax.swing.JFrame {
   /* Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    */

    /**
     * Creates new form Patients_Detail
     */
    public Patients_Detail() {
        initComponents();
        
        //conn=javaconnect.ConnectDB();
        updateTable();
        setIcon();
        
                  txt_table.getTableHeader().setFont(new Font("Tohoma", Font.BOLD, 12));
                  check();
       // increment();
        //txt_d_btn.setEnabled(false);
        //txt_add.setEnabled(false);
       // txt_add.setEnabled(false);
        //txt_s_search_btn.setEnabled(false);
        //txt_update_btn.setEnabled(false);
       /* txt_p_id.setText("HM-0");
        txt_Doctor_id.setText("DI-0");*/
        
        
    }
    public void check()
    {
         Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
     conn=javaconnect.ConnectDB();
        try
        {
             
            //b_nom.getText();
            String a="OPD-3000";
            // b_nom.setText("MH-3000");
          //  String check= b_nom.getText();
            for(int i=0;i<1000;i++)
            {
            String sql="select patient_id from Patient_table where patient_id>'"+a+"'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next())
            {
               
               a=rs.getString("patient_id");
              
            }
        }
            //b_nom.setText(a);
            String value=a;
            String va2=value.replaceAll("OPD-", "");
            int VALUE=Integer.parseInt(va2);
            ++VALUE;
             txt_p_id.setText("OPD-"+VALUE);
            /*
             String VALUE    ="MH-1001";
        String v2=VALUE.replaceAll("MH-", "");
        int value=Integer.parseInt(v2);
        ++value;
        JOptionPane.showMessageDialog(null, "my replace code is\n\t\t\tMH-"+value);
            */
                    
                    
                    
            
            
            
        }
        catch(NumberFormatException | SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex+"\nConnection error\n\tplease check out");
        }
        finally
        {
            try
            {
              if(rs!=null)
              {
                  rs.close();
                  
              }
              if(pst!=null)
              {
                  pst.close();
              }
              if(conn!=null)
              {
                  conn.close();
              }
            }
            catch(SQLException e)
            {
               JOptionPane.showMessageDialog(null, e);
            }
        }
    }
     
    
   public void setIcon()
    {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo-nonetext.png")));
    }
    
    private void updateTable()
    {
          Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
     conn=javaconnect.ConnectDB();
        try
        {
            
            String sql="select * from Patient_table order by patient_id asc";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            txt_table.setModel(DbUtils.resultSetToTableModel(rs));
           // rs=pst.executeQuery();

        }
         catch(SQLException e)
         {
             JOptionPane.showMessageDialog(null,e+"\nConnection Error\nplease check..");
         }
        finally
        {
            try
            {
              if(rs!=null)
              {
                  rs.close();
                  
              }
              if(pst!=null)
              {
                  pst.close();
              }
              if(conn!=null)
              {
                  conn.close();
              }
            }
            catch(SQLException e)
            {
               JOptionPane.showMessageDialog(null, e);
            }
        }
        
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_p_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_first_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_second_name = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_age = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_weight = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_address = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_mobile = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_disease = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_Doctor_id = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pd_date = new com.toedter.calendar.JDateChooser();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        blood_group = new javax.swing.JComboBox<>();
        g_add = new javax.swing.JComboBox<>();
        jButton9 = new javax.swing.JButton();
        dob_add = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        txt_update_id = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        txt_update_doctor = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        txt_update_first_name = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        txt_update_last = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        txt_update_age = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        txt_update_weight = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        txt_update_mobile = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        txt_update_address = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        txt_update_disease = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txt_update_search_l = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        update_date = new com.toedter.calendar.JDateChooser();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        blood_group3 = new javax.swing.JComboBox<>();
        update_gender = new javax.swing.JComboBox<>();
        update_btn = new javax.swing.JButton();
        update_dob = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txt_search_s = new javax.swing.JButton();
        txt_s_search = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt_s_id = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txt_s_doctor_id = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txt_s_name = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txt_s_last_name = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txt_s_age = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txt_s_weight = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txt_c_mobile = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txt_s_address = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txt_s_disease = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        txt_s_search_btn = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        blood_group2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        sp_date = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        txt_d_search = new javax.swing.JButton();
        jLabel55 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel54 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        d_doctor_id = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        d_first_name = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        d_last_name = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        d_age = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        d_weight = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        d_mobile = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        d_address = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        d_disease = new javax.swing.JTextField();
        jLabel69 = new javax.swing.JLabel();
        d_patient_id = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        blood_group1 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        d_botton = new javax.swing.JButton();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Patient Details");
        setSize(new java.awt.Dimension(7000, 7000));

        jTabbedPane1.setForeground(new java.awt.Color(0, 102, 102));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(55, 49, 49));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Add Patient");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(200, 0, 820, 168);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 190, 170);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home-icon (1).png"))); // NOI18N
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(1280, 20, 60, 60);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hospital-Top-Slider-Image.jpg"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(170, 20, 1210, 170);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Patient ID");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 250, 100, 30);

        txt_p_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_p_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_p_idKeyTyped(evt);
            }
        });
        jPanel1.add(txt_p_id);
        txt_p_id.setBounds(170, 250, 170, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("First Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 315, 100, 30);

        txt_first_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txt_first_name);
        txt_first_name.setBounds(170, 315, 170, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Last Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(430, 315, 110, 30);

        txt_second_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txt_second_name);
        txt_second_name.setBounds(580, 315, 180, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Age");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(490, 375, 40, 30);

        txt_age.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txt_age);
        txt_age.setBounds(580, 375, 120, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Weight");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(60, 435, 80, 30);

        txt_weight.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txt_weight);
        txt_weight.setBounds(170, 435, 120, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("Gender");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(470, 435, 80, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("Address");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(50, 495, 80, 30);

        txt_address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txt_address);
        txt_address.setBounds(170, 495, 260, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("Mobile");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(480, 495, 70, 30);

        txt_mobile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txt_mobile);
        txt_mobile.setBounds(580, 495, 200, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setText("Disease");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(50, 555, 80, 30);

        txt_disease.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txt_disease);
        txt_disease.setBounds(170, 555, 170, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("Doctor ID");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(430, 250, 100, 30);

        txt_Doctor_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txt_Doctor_id);
        txt_Doctor_id.setBounds(580, 250, 180, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setText("Date");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(70, 620, 50, 30);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor-patient-icon-Icon_PatientReviewsRetina.png"))); // NOI18N
        jLabel15.setText("jLabel15");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(720, 180, 540, 420);

        pd_date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(pd_date);
        pd_date.setBounds(170, 620, 180, 30);

        jLabel72.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(0, 102, 102));
        jLabel72.setText("D.O.B");
        jPanel1.add(jLabel72);
        jLabel72.setBounds(70, 375, 60, 30);

        jLabel73.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(0, 102, 102));
        jLabel73.setText("Blood Group");
        jPanel1.add(jLabel73);
        jLabel73.setBounds(430, 555, 110, 30);

        blood_group.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        blood_group.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----none----", "AB+", "AB-", "A+", "A-", "B+", "B-", "O+", "O-" }));
        jPanel1.add(blood_group);
        blood_group.setBounds(580, 555, 180, 30);

        g_add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        g_add.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----none----", "Male", "Female" }));
        jPanel1.add(g_add);
        g_add.setBounds(580, 435, 120, 30);

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 102, 102));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Device-Floppy-icon.png"))); // NOI18N
        jButton9.setText("Save");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(1000, 600, 130, 50);

        dob_add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(dob_add);
        dob_add.setBounds(170, 375, 170, 30);

        jTabbedPane1.addTab("Add Patient", jPanel1);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.png"))); // NOI18N
        jPanel3.add(jLabel37);
        jLabel37.setBounds(0, 0, 190, 170);

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 102, 102));
        jLabel40.setText("Patient ID");
        jPanel3.add(jLabel40);
        jLabel40.setBounds(40, 250, 100, 30);

        txt_update_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(txt_update_id);
        txt_update_id.setBounds(170, 250, 170, 30);

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 102, 102));
        jLabel39.setText("Doctor ID");
        jPanel3.add(jLabel39);
        jLabel39.setBounds(430, 250, 110, 30);

        txt_update_doctor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(txt_update_doctor);
        txt_update_doctor.setBounds(580, 250, 180, 30);

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 102, 102));
        jLabel41.setText("First Name");
        jPanel3.add(jLabel41);
        jLabel41.setBounds(30, 315, 100, 30);

        txt_update_first_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(txt_update_first_name);
        txt_update_first_name.setBounds(170, 315, 170, 30);

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 102, 102));
        jLabel42.setText("Last Name");
        jPanel3.add(jLabel42);
        jLabel42.setBounds(430, 315, 100, 30);

        txt_update_last.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(txt_update_last);
        txt_update_last.setBounds(580, 315, 180, 30);

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 102, 102));
        jLabel43.setText("Age");
        jPanel3.add(jLabel43);
        jLabel43.setBounds(490, 375, 40, 30);

        txt_update_age.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(txt_update_age);
        txt_update_age.setBounds(580, 375, 120, 30);

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 102, 102));
        jLabel44.setText("Weight");
        jPanel3.add(jLabel44);
        jLabel44.setBounds(60, 435, 80, 30);

        txt_update_weight.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(txt_update_weight);
        txt_update_weight.setBounds(170, 435, 130, 30);

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 102, 102));
        jLabel45.setText("Gender");
        jPanel3.add(jLabel45);
        jLabel45.setBounds(470, 435, 70, 30);

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 102, 102));
        jLabel46.setText("Mobile");
        jPanel3.add(jLabel46);
        jLabel46.setBounds(480, 495, 60, 30);

        txt_update_mobile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(txt_update_mobile);
        txt_update_mobile.setBounds(580, 495, 200, 30);

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(0, 102, 102));
        jLabel47.setText("Address");
        jPanel3.add(jLabel47);
        jLabel47.setBounds(50, 495, 80, 30);

        txt_update_address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(txt_update_address);
        txt_update_address.setBounds(170, 495, 260, 30);

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 102, 102));
        jLabel49.setText("Date");
        jPanel3.add(jLabel49);
        jLabel49.setBounds(60, 620, 60, 30);

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(0, 102, 102));
        jLabel50.setText("Disease");
        jPanel3.add(jLabel50);
        jLabel50.setBounds(50, 555, 80, 30);

        txt_update_disease.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(txt_update_disease);
        txt_update_disease.setBounds(170, 555, 170, 30);

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor-patient-icon-Icon_PatientReviewsRetina.png"))); // NOI18N
        jPanel3.add(jLabel51);
        jLabel51.setBounds(720, 180, 530, 420);

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("Update Patient");
        jPanel3.add(jLabel53);
        jLabel53.setBounds(190, 40, 377, 90);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("Search");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(1110, 30, 100, 40);

        txt_update_search_l.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(txt_update_search_l);
        txt_update_search_l.setBounds(900, 30, 180, 40);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home-icon (1).png"))); // NOI18N
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);
        jButton6.setBounds(1280, 20, 60, 60);

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 102, 102));
        jLabel35.setText("Patient ID");
        jPanel3.add(jLabel35);
        jLabel35.setBounds(790, 30, 100, 40);

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hospital-Top-Slider-Image.jpg"))); // NOI18N
        jPanel3.add(jLabel38);
        jLabel38.setBounds(170, 20, 1208, 170);

        update_date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(update_date);
        update_date.setBounds(170, 620, 190, 30);

        jLabel76.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(0, 102, 102));
        jLabel76.setText("D.O.B");
        jPanel3.add(jLabel76);
        jLabel76.setBounds(70, 375, 60, 30);

        jLabel77.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(0, 102, 102));
        jLabel77.setText("Blood Group");
        jPanel3.add(jLabel77);
        jLabel77.setBounds(430, 555, 110, 30);

        blood_group3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        blood_group3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----none----", "AB+", "AB-", "A+", "A-", "B+", "B-", "O+", "O-" }));
        jPanel3.add(blood_group3);
        blood_group3.setBounds(580, 555, 180, 30);

        update_gender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        update_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----none----", "Male", "Female" }));
        jPanel3.add(update_gender);
        update_gender.setBounds(580, 435, 120, 30);

        update_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        update_btn.setForeground(new java.awt.Color(0, 102, 102));
        update_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Actions-edit-redo-icon (1).png"))); // NOI18N
        update_btn.setText("Update");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });
        jPanel3.add(update_btn);
        update_btn.setBounds(1000, 600, 140, 40);

        update_dob.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(update_dob);
        update_dob.setBounds(170, 375, 170, 30);

        jTabbedPane1.addTab("Update Patient", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);
        jPanel4.add(jLabel19);
        jLabel19.setBounds(323, 153, 0, 0);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.png"))); // NOI18N
        jPanel4.add(jLabel20);
        jLabel20.setBounds(0, 0, 190, 170);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Search Patient");
        jPanel4.add(jLabel23);
        jLabel23.setBounds(190, 0, 400, 160);

        txt_search_s.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_search_s.setForeground(new java.awt.Color(0, 102, 102));
        txt_search_s.setText("Search");
        txt_search_s.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt_search_s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_search_sActionPerformed(evt);
            }
        });
        jPanel4.add(txt_search_s);
        txt_search_s.setBounds(1150, 30, 110, 40);

        txt_s_search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(txt_s_search);
        txt_s_search.setBounds(950, 30, 180, 40);

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 102, 102));
        jLabel32.setText("Patient ID");
        jPanel4.add(jLabel32);
        jLabel32.setBounds(840, 30, 100, 40);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home-icon (1).png"))); // NOI18N
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5);
        jButton5.setBounds(1280, 20, 60, 60);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hospital-Top-Slider-Image.jpg"))); // NOI18N
        jPanel4.add(jLabel21);
        jLabel21.setBounds(170, 20, 1208, 170);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 102, 102));
        jLabel22.setText("Patient ID");
        jPanel4.add(jLabel22);
        jLabel22.setBounds(40, 250, 100, 30);

        txt_s_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(txt_s_id);
        txt_s_id.setBounds(170, 250, 170, 30);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 102, 102));
        jLabel24.setText("Doctor ID");
        jPanel4.add(jLabel24);
        jLabel24.setBounds(430, 250, 100, 30);

        txt_s_doctor_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(txt_s_doctor_id);
        txt_s_doctor_id.setBounds(580, 250, 180, 30);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 102, 102));
        jLabel25.setText("First Name");
        jPanel4.add(jLabel25);
        jLabel25.setBounds(30, 315, 100, 30);

        txt_s_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(txt_s_name);
        txt_s_name.setBounds(170, 315, 170, 30);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 102, 102));
        jLabel26.setText("Last Name");
        jPanel4.add(jLabel26);
        jLabel26.setBounds(430, 315, 110, 30);

        txt_s_last_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(txt_s_last_name);
        txt_s_last_name.setBounds(580, 315, 180, 30);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 102, 102));
        jLabel27.setText("Age");
        jPanel4.add(jLabel27);
        jLabel27.setBounds(490, 375, 40, 30);

        txt_s_age.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(txt_s_age);
        txt_s_age.setBounds(580, 375, 120, 30);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 102, 102));
        jLabel28.setText("Weight");
        jPanel4.add(jLabel28);
        jLabel28.setBounds(60, 435, 80, 30);

        txt_s_weight.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(txt_s_weight);
        txt_s_weight.setBounds(170, 435, 120, 30);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 102, 102));
        jLabel29.setText("Gender");
        jPanel4.add(jLabel29);
        jLabel29.setBounds(470, 435, 80, 30);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 102, 102));
        jLabel30.setText("Mobile");
        jPanel4.add(jLabel30);
        jLabel30.setBounds(470, 495, 70, 30);

        txt_c_mobile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(txt_c_mobile);
        txt_c_mobile.setBounds(580, 495, 200, 30);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 102, 102));
        jLabel31.setText("Address");
        jPanel4.add(jLabel31);
        jLabel31.setBounds(50, 495, 80, 30);

        txt_s_address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(txt_s_address);
        txt_s_address.setBounds(170, 495, 260, 30);

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 102, 102));
        jLabel33.setText("Date");
        jPanel4.add(jLabel33);
        jLabel33.setBounds(60, 620, 60, 30);

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 102, 102));
        jLabel34.setText("Disease");
        jPanel4.add(jLabel34);
        jLabel34.setBounds(50, 555, 80, 30);

        txt_s_disease.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(txt_s_disease);
        txt_s_disease.setBounds(170, 555, 170, 30);

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor-patient-icon-Icon_PatientReviewsRetina.png"))); // NOI18N
        jLabel36.setText("jLabel36");
        jPanel4.add(jLabel36);
        jLabel36.setBounds(720, 180, 530, 420);

        txt_s_search_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_s_search_btn.setForeground(new java.awt.Color(0, 102, 102));
        txt_s_search_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button-Refresh-icon (1).png"))); // NOI18N
        txt_s_search_btn.setText("Clear");
        txt_s_search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_s_search_btnActionPerformed(evt);
            }
        });
        jPanel4.add(txt_s_search_btn);
        txt_s_search_btn.setBounds(1000, 610, 120, 40);

        jDateChooser1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(jDateChooser1);
        jDateChooser1.setBounds(170, 620, 180, 30);

        jLabel74.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(0, 102, 102));
        jLabel74.setText("D.O.B");
        jPanel4.add(jLabel74);
        jLabel74.setBounds(70, 375, 70, 30);

        jLabel75.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(0, 102, 102));
        jLabel75.setText("Blood Group");
        jPanel4.add(jLabel75);
        jLabel75.setBounds(430, 555, 110, 30);

        blood_group2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        blood_group2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----none----", "AB+", "AB-", "A+", "A-", "B+", "B-", "O+", "O-" }));
        jPanel4.add(blood_group2);
        blood_group2.setBounds(580, 555, 180, 30);

        jComboBox3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----none----", "Male", "Female" }));
        jPanel4.add(jComboBox3);
        jComboBox3.setBounds(580, 435, 120, 30);

        sp_date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(sp_date);
        sp_date.setBounds(170, 375, 170, 30);

        jTabbedPane1.addTab("Search Patient", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.setLayout(null);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.png"))); // NOI18N
        jPanel5.add(jLabel16);
        jLabel16.setBounds(0, 0, 190, 170);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("View Patient");
        jPanel5.add(jLabel17);
        jLabel17.setBounds(190, 0, 430, 170);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 102));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home-icon (1).png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2);
        jButton2.setBounds(1280, 20, 60, 60);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hospital-Top-Slider-Image.jpg"))); // NOI18N
        jPanel5.add(jLabel18);
        jLabel18.setBounds(170, 20, 1210, 170);

        txt_table.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_table.setForeground(new java.awt.Color(0, 102, 102));
        txt_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        txt_table.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt_table.setRowHeight(30);
        txt_table.setRowMargin(2);
        jScrollPane2.setViewportView(txt_table);

        jPanel5.add(jScrollPane2);
        jScrollPane2.setBounds(0, 190, 1380, 530);

        jTabbedPane1.addTab("View Patient", jPanel5);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.png"))); // NOI18N
        jPanel2.add(jLabel52);
        jLabel52.setBounds(0, 0, 190, 170);

        txt_d_search.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_d_search.setForeground(new java.awt.Color(0, 102, 102));
        txt_d_search.setText("Search");
        txt_d_search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt_d_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_d_searchActionPerformed(evt);
            }
        });
        jPanel2.add(txt_d_search);
        txt_d_search.setBounds(1090, 30, 120, 40);

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("Delete Patient");
        jPanel2.add(jLabel55);
        jLabel55.setBounds(200, 0, 520, 168);

        txt_search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_search.setToolTipText("Enter Petient ID");
        jPanel2.add(txt_search);
        txt_search.setBounds(890, 30, 180, 40);

        jLabel66.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(0, 102, 102));
        jLabel66.setText("Patient ID");
        jPanel2.add(jLabel66);
        jLabel66.setBounds(780, 30, 110, 40);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 102));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home-icon (1).png"))); // NOI18N
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(1280, 20, 60, 60);

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hospital-Top-Slider-Image.jpg"))); // NOI18N
        jPanel2.add(jLabel54);
        jLabel54.setBounds(170, 20, 12110, 170);

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(0, 102, 102));
        jLabel56.setText("Patient ID");
        jPanel2.add(jLabel56);
        jLabel56.setBounds(40, 250, 100, 30);
        jPanel2.add(jLabel57);
        jLabel57.setBounds(30, 320, 0, 0);

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(0, 102, 102));
        jLabel58.setText("Doctor ID");
        jPanel2.add(jLabel58);
        jLabel58.setBounds(440, 250, 100, 30);

        d_doctor_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(d_doctor_id);
        d_doctor_id.setBounds(580, 250, 180, 30);

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(0, 102, 102));
        jLabel59.setText("First Name");
        jPanel2.add(jLabel59);
        jLabel59.setBounds(30, 315, 100, 30);

        d_first_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(d_first_name);
        d_first_name.setBounds(170, 315, 170, 30);

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(0, 102, 102));
        jLabel60.setText("Last Name");
        jPanel2.add(jLabel60);
        jLabel60.setBounds(430, 315, 100, 30);

        d_last_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(d_last_name);
        d_last_name.setBounds(580, 315, 180, 30);

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(0, 102, 102));
        jLabel61.setText("Age");
        jPanel2.add(jLabel61);
        jLabel61.setBounds(490, 375, 40, 30);

        d_age.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(d_age);
        d_age.setBounds(580, 375, 120, 30);

        jLabel62.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(0, 102, 102));
        jLabel62.setText("Weight");
        jPanel2.add(jLabel62);
        jLabel62.setBounds(60, 435, 80, 30);

        d_weight.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(d_weight);
        d_weight.setBounds(170, 435, 120, 30);

        jLabel63.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(0, 102, 102));
        jLabel63.setText("Gender");
        jPanel2.add(jLabel63);
        jLabel63.setBounds(460, 435, 80, 30);

        jLabel64.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(0, 102, 102));
        jLabel64.setText("Mobile");
        jPanel2.add(jLabel64);
        jLabel64.setBounds(470, 495, 70, 30);

        d_mobile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(d_mobile);
        d_mobile.setBounds(580, 495, 200, 30);

        jLabel65.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(0, 102, 102));
        jLabel65.setText("Address");
        jPanel2.add(jLabel65);
        jLabel65.setBounds(50, 495, 80, 30);

        d_address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(d_address);
        d_address.setBounds(170, 495, 260, 30);

        jLabel67.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(0, 102, 102));
        jLabel67.setText("Date");
        jPanel2.add(jLabel67);
        jLabel67.setBounds(60, 620, 60, 30);

        jLabel68.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(0, 102, 102));
        jLabel68.setText("Blood Group");
        jPanel2.add(jLabel68);
        jLabel68.setBounds(430, 555, 110, 30);

        d_disease.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(d_disease);
        d_disease.setBounds(170, 555, 170, 30);

        jLabel69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor-patient-icon-Icon_PatientReviewsRetina.png"))); // NOI18N
        jLabel69.setText("jLabel69");
        jPanel2.add(jLabel69);
        jLabel69.setBounds(720, 180, 530, 420);

        d_patient_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(d_patient_id);
        d_patient_id.setBounds(170, 250, 170, 30);

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 102, 102));
        jLabel48.setText("Patient ID");
        jPanel2.add(jLabel48);
        jLabel48.setBounds(840, 30, 110, 40);

        jDateChooser3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(jDateChooser3);
        jDateChooser3.setBounds(170, 620, 210, 30);

        jLabel70.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(0, 102, 102));
        jLabel70.setText("D.O.B");
        jPanel2.add(jLabel70);
        jLabel70.setBounds(70, 375, 70, 30);

        jLabel71.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(0, 102, 102));
        jLabel71.setText("Disease");
        jPanel2.add(jLabel71);
        jLabel71.setBounds(50, 555, 80, 30);

        blood_group1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        blood_group1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----none----", "AB+", "AB-", "A+", "A-", "B+", "B-", "O+", "O-" }));
        jPanel2.add(blood_group1);
        blood_group1.setBounds(580, 555, 180, 30);

        jComboBox4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----none----", "Male", "Female" }));
        jPanel2.add(jComboBox4);
        jComboBox4.setBounds(580, 435, 120, 30);

        d_botton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        d_botton.setForeground(new java.awt.Color(0, 102, 102));
        d_botton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cross-icon.png"))); // NOI18N
        d_botton.setText("Delete");
        d_botton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d_bottonActionPerformed(evt);
            }
        });
        jPanel2.add(d_botton);
        d_botton.setBounds(1000, 600, 127, 40);
        jPanel2.add(jDateChooser2);
        jDateChooser2.setBounds(170, 375, 170, 30);

        jTabbedPane1.addTab("Delete Patient", jPanel2);

        jScrollPane1.setViewportView(jTabbedPane1);

        jScrollPane3.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1377, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_d_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_d_searchActionPerformed
        // TODO add your handling code here:
        String sql="select * from Patient_table where patient_id=?";
        String st=txt_search.getText();
           Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
     conn=javaconnect.ConnectDB();
       
        try
        {
             if(st.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Search Field id Blank");
            
        }
        else
        {
           
            pst=conn.prepareStatement(sql);
            pst.setString(1,txt_search.getText());
            rs=pst.executeQuery();
            if(rs.next())
            {
                String a=rs.getString("patient_id");
                d_patient_id.setText(a);
                 String b=rs.getString("patient_name");
                d_first_name.setText(b);
                 String c=rs.getString("age");
                d_age.setText(c);
                 String d=rs.getString("weight");
                d_weight.setText(d);
                 String e=rs.getString("gender");
                jComboBox4.setSelectedItem(e);
                 String f=rs.getString("address");
                d_address.setText(f);
                 String g=rs.getString("mobile");
                d_mobile.setText(g);
                 String h=rs.getString("disease");
                d_disease.setText(h);
                 String i=rs.getString("doctor_id");
                d_doctor_id.setText(i);
                 String j=rs.getString("Date");
                 ((JTextField)jDateChooser3.getDateEditor().getUiComponent()).setText(j);
                 String k=rs.getString("last_name");
                d_last_name.setText(k);
                String l=rs.getString("BOD");
                ((JTextField)jDateChooser2.getDateEditor().getUiComponent()).setText(j);
                String m=rs.getString("blood_group");
                blood_group1.setSelectedItem(m);
                 d_botton.setEnabled(true);
                 updateTable();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Sorry No result found");
            }
        }
           
        }
        
        catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,e+"\n (D) Connection Error\nplease check..");
        }
        
       finally
        {
            try
            {
              if(rs!=null)
              {
                  rs.close();
                  
              }
              if(pst!=null)
              {
                  pst.close();
              }
              if(conn!=null)
              {
                  conn.close();
              }
            }
            catch(SQLException e)
            {
               JOptionPane.showMessageDialog(null, e);
            }
        }
         
        
            
    }//GEN-LAST:event_txt_d_searchActionPerformed

    private void txt_search_sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_search_sActionPerformed
        // TODO add your handling code here:
        String sql="select * from Patient_table where patient_id=?";
          Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
     conn=javaconnect.ConnectDB();
        try
        {
            
            String st=txt_s_search.getText();
            if(st.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Serch Field is Empty");
                
            }
            else
            {
            pst=conn.prepareStatement(sql);
            pst.setString(1,txt_s_search.getText());
            rs=pst.executeQuery();
            if(rs.next())
            {
                String a=rs.getString("patient_id");
                txt_s_id.setText(a);
                String b=rs.getString("patient_name");
                txt_s_name.setText(b);
                String c=rs.getString("age");
                txt_s_age.setText(c); 
                String d=rs.getString("gender");
                jComboBox3.setSelectedItem(d);
                String e=rs.getString("weight");
                txt_s_weight.setText(e);
                String f=rs.getString("address");
                txt_s_address.setText(f);
                String g=rs.getString("mobile");
                txt_c_mobile.setText(g);
                String h=rs.getString("disease");
                txt_s_disease.setText(h);
                String i=rs.getString("doctor_id");
                txt_s_doctor_id.setText(i);
                 String j=rs.getString("Date");
                ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).setText(j);
               
                String k=rs.getString("last_name");
                txt_s_last_name.setText(k);
                String l=rs.getString("BOD");
                ((JTextField)sp_date.getDateEditor().getUiComponent()).setText(j);
                String m=rs.getString("blood_group");
                blood_group2.setSelectedItem(m);
                txt_s_search_btn.setEnabled(true);
                updateTable();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Sorry No result found");
            }
            }
        }
        
        catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,e+"\n (s) Connection Error\nplease check.." );
            
            
                    
        }
       finally
        {
            try
            {
              if(rs!=null)
              {
                  rs.close();
                  
              }
              if(pst!=null)
              {
                  pst.close();
              }
              if(conn!=null)
              {
                  conn.close();
              }
            }
            catch(SQLException e)
            {
               JOptionPane.showMessageDialog(null, e);
            }
        }
        
        
            
    }//GEN-LAST:event_txt_search_sActionPerformed

    private void txt_s_search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_s_search_btnActionPerformed
        // TODO add your handling code here:
        
                txt_s_id.setText("");
           
                txt_s_name.setText("");
           
                txt_s_age.setText("");

                jComboBox3.setSelectedItem("");
          
                txt_s_weight.setText("");

                txt_s_address.setText("");
             
                txt_c_mobile.setText("");
             
                txt_s_disease.setText("");
                jComboBox3.setSelectedIndex(0);
                blood_group2.setSelectedIndex(0);
              
                txt_s_doctor_id.setText("");
               
               ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).setText("");
               blood_group2.setSelectedItem("");
             
                ((JTextField)sp_date.getDateEditor().getUiComponent()).setText("");
                txt_s_last_name.setText("");
                txt_s_search_btn.setEnabled(false);
        
                
        
        
    }//GEN-LAST:event_txt_s_search_btnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         // TODO add your handling code here:
        String sql="select * from Patient_table where patient_id='"+txt_update_search_l.getText()+"'";
        Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
     conn=javaconnect.ConnectDB();
        try
        {
            
            String st=txt_update_search_l.getText();
            if(st.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Search Field is Empty");
            }
            else
            {
                  
                
            
            pst=conn.prepareStatement(sql);
           // pst.setString(1,txt_update_search_l.getText());
            rs=pst.executeQuery();
            if(rs.next())
            {
                String a=rs.getString("patient_id");
                txt_update_id.setText(a);
                String b=rs.getString("patient_name");
                txt_update_first_name.setText(b);
                String c=rs.getString("age");
                txt_update_age.setText(c);
                String d=rs.getString("gender");
                update_gender.setSelectedItem(d);
                String e=rs.getString("weight");
                txt_update_weight.setText(e);
                String f=rs.getString("address");
                txt_update_address.setText(f);
                String g=rs.getString("mobile");
                txt_update_mobile.setText(g);
                String h=rs.getString("disease");
                txt_update_disease.setText(h);
                String i=rs.getString("doctor_id");
                txt_update_doctor.setText(i);
                String j=rs.getString("Date");
               ((JTextField)update_date.getDateEditor().getUiComponent()).setText(j);
                String k=rs.getString("last_name");
                txt_update_last.setText(k);
                String l=rs.getString("BOD");
                ((JTextField)update_dob.getDateEditor().getUiComponent()).setText(j);
                String m=rs.getString("blood_group");
                blood_group3.setSelectedItem(m);
                txt_s_search_btn.setEnabled(true);
                update_btn.setEnabled(true);
                 updateTable();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Sorry No result found");
            }
            }
        }
        
        catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,e+"\nConnection Error\nplease check.." );
            
            
                    
        }
        finally
        {
            try
            {
              if(rs!=null)
              {
                  rs.close();
                  
              }
              if(pst!=null)
              {
                  pst.close();
              }
              if(conn!=null)
              {
                  conn.close();
              }
            }
            catch(SQLException e)
            {
               JOptionPane.showMessageDialog(null, e);
            }
        }
        
        
           
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Origine().setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_p_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_p_idKeyTyped
        // TODO add your handling code here:
        /*if(txt_p_id.getText().equals("")) {
    txt_add.setEnabled(false);
}else {
    txt_add.setEnabled(true);
}*/
    }//GEN-LAST:event_txt_p_idKeyTyped

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Origine().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        dispose();
  
        new Origine().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Origine().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Origine().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void d_bottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d_bottonActionPerformed
        // TODO add your handling code here:
        /*
        delete action will perform here//
        
        */
         Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
     conn=javaconnect.ConnectDB();
        try
        {
            if(txt_search.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Please Enter Patient Id first");
            }
            else
            {
                 
                String del=txt_search.getText();
                String sql="delete from Patient_table where patient_id='"+del+"'";
                 pst=conn.prepareStatement(sql);
           
            pst.execute();
            JOptionPane.showMessageDialog(null, "Deleted Successfully");
             updateTable();
            
            }
        }
        catch(HeadlessException | SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
        finally
        {
            try
            {
              if(rs!=null)
              {
                  rs.close();
                  
              }
              if(pst!=null)
              {
                  pst.close();
              }
              if(conn!=null)
              {
                  conn.close();
              }
            }
            catch(SQLException e)
            {
               JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_d_bottonActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        /*
        ADDING DATA
        */
         Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;  
     conn=javaconnect.ConnectDB();
        try
        {
            if(txt_p_id.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Enter Patient Id First");
            }
            else if(txt_Doctor_id.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Enter Doctor Id First");
            }
            else
            {
              
            
            String sql="insert into Patient_table values(?,?,?,?,?,?,?,?,?,?,?,?,?)";
            pst=conn.prepareStatement(sql);
            pst.setString(1,((JTextField)pd_date.getDateEditor().getUiComponent()).getText());
            pst.setString(2, txt_p_id.getText());
            pst.setString(3, txt_Doctor_id.getText());
            pst.setString(4, txt_first_name.getText());
            pst.setString(5, txt_second_name.getText());
            pst.setString(6, txt_age.getText());
            pst.setString(7, txt_weight.getText());
            pst.setString(8, g_add.getSelectedItem().toString());
            pst.setString(9, txt_mobile.getText());
            pst.setString(10, txt_address.getText());
            pst.setString(11, txt_disease.getText());
            pst.setString(12, ((JTextField)dob_add.getDateEditor().getUiComponent()).getText());
            pst.setString(13, blood_group.getSelectedItem().toString());
            int p=JOptionPane.showConfirmDialog(null,"Do you want to save","Conform Save",JOptionPane.YES_NO_OPTION);
             if(p==0)
             { 
              pst.execute();
             JOptionPane.showMessageDialog(null, "Saved");  
            
              String VALUE=txt_p_id.getText();
             String v2=VALUE.replaceAll("OPD-", "");
        int value=Integer.parseInt(v2);
        ++value;
         updateTable();
            txt_p_id.setText("OPD-"+value);
             ((JTextField)pd_date.getDateEditor().getUiComponent()).setText("");
             txt_Doctor_id.setText("");
             txt_first_name.setText("");
             txt_second_name.setText("");
             txt_age.setText("");
             txt_weight.setText("");
             g_add.setSelectedIndex(0);
             txt_mobile.setText("");
             txt_address.setText("");
             txt_disease.setText("");
             ((JTextField)dob_add.getDateEditor().getUiComponent()).setText("");
             blood_group.setSelectedIndex(0);
             }
            }
        }
        catch(HeadlessException | NumberFormatException | SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex);
            
        }
        finally
        {
            try
            {
              if(rs!=null)
              {
                  rs.close();
                  
              }
              if(pst!=null)
              {
                  pst.close();
              }
              if(conn!=null)
              {
                  conn.close();
              }
            }
            catch(SQLException e)
            {
               JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        // TODO add your handling code here:
        /*
        update table
        */
       String a=((JTextField)update_date.getDateEditor().getUiComponent()).getText();
        String b=txt_update_id.getText();
        String c=txt_update_doctor.getText();
       String d= txt_update_first_name.getText();
        String e=txt_update_last.getText();
          String f=((JTextField)update_dob.getDateEditor().getUiComponent()).getText();
        String g=txt_update_age.getText();
        String h=txt_update_weight.getText();
        String i=update_gender.getSelectedItem().toString();
        String j=txt_update_mobile.getText();
        String k=txt_update_address.getText();
        String l=txt_update_disease.getText();
        String m=blood_group3.getSelectedItem().toString();
         Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
     conn=javaconnect.ConnectDB();
        
        try
        {
            if(b.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Patient id is Empty");
            }
            else
                if(c.isEmpty())
                {
                    JOptionPane.showMessageDialog(null, "Doctor id is Empty");
                }
            else
                {
                     
            String sql="update Patient_table set Date='"+a+"',patient_id='"+b+"',doctor_id='"+c+"',patient_name='"+d+"',last_name='"+e+"',age='"+g+"',weight='"+h+"',gender='"+i+"',mobile='"+j+"',address='"+k+"',disease='"+l+"',BOD='"+f+"',blood_group='"+m+"'where patient_id='"+b+"'";
              pst=conn.prepareStatement(sql);
            pst.execute();
             JOptionPane.showMessageDialog(null,"UPDATED");
             updateTable();
                }
        }
        catch(HeadlessException | SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
        finally
        {
            try
            {
              if(rs!=null)
              {
                  rs.close();
                  
              }
              if(pst!=null)
              {
                  pst.close();
              }
              if(conn!=null)
              {
                  conn.close();
              }
            }
            catch(SQLException ex)
            {
               JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_update_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patients_Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patients_Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patients_Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patients_Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Patients_Detail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> blood_group;
    private javax.swing.JComboBox<String> blood_group1;
    private javax.swing.JComboBox<String> blood_group2;
    private javax.swing.JComboBox<String> blood_group3;
    private javax.swing.JTextField d_address;
    private javax.swing.JTextField d_age;
    private javax.swing.JButton d_botton;
    private javax.swing.JTextField d_disease;
    private javax.swing.JTextField d_doctor_id;
    private javax.swing.JTextField d_first_name;
    private javax.swing.JTextField d_last_name;
    private javax.swing.JTextField d_mobile;
    private javax.swing.JTextField d_patient_id;
    private javax.swing.JTextField d_weight;
    private com.toedter.calendar.JDateChooser dob_add;
    private javax.swing.JComboBox<String> g_add;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.toedter.calendar.JDateChooser pd_date;
    private com.toedter.calendar.JDateChooser sp_date;
    private javax.swing.JTextField txt_Doctor_id;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_c_mobile;
    private javax.swing.JButton txt_d_search;
    private javax.swing.JTextField txt_disease;
    private javax.swing.JTextField txt_first_name;
    private javax.swing.JTextField txt_mobile;
    private javax.swing.JTextField txt_p_id;
    private javax.swing.JTextField txt_s_address;
    private javax.swing.JTextField txt_s_age;
    private javax.swing.JTextField txt_s_disease;
    private javax.swing.JTextField txt_s_doctor_id;
    private javax.swing.JTextField txt_s_id;
    private javax.swing.JTextField txt_s_last_name;
    private javax.swing.JTextField txt_s_name;
    private javax.swing.JTextField txt_s_search;
    private javax.swing.JButton txt_s_search_btn;
    private javax.swing.JTextField txt_s_weight;
    private javax.swing.JTextField txt_search;
    private javax.swing.JButton txt_search_s;
    private javax.swing.JTextField txt_second_name;
    private javax.swing.JTable txt_table;
    private javax.swing.JTextField txt_update_address;
    private javax.swing.JTextField txt_update_age;
    private javax.swing.JTextField txt_update_disease;
    private javax.swing.JTextField txt_update_doctor;
    private javax.swing.JTextField txt_update_first_name;
    private javax.swing.JTextField txt_update_id;
    private javax.swing.JTextField txt_update_last;
    private javax.swing.JTextField txt_update_mobile;
    private javax.swing.JTextField txt_update_search_l;
    private javax.swing.JTextField txt_update_weight;
    private javax.swing.JTextField txt_weight;
    private javax.swing.JButton update_btn;
    private com.toedter.calendar.JDateChooser update_date;
    private com.toedter.calendar.JDateChooser update_dob;
    private javax.swing.JComboBox<String> update_gender;
    // End of variables declaration//GEN-END:variables
}
