
import java.awt.HeadlessException;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.sql.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Payment extends javax.swing.JFrame {
    /*Connection conn=null;
    ResultSet rs=null;
   PreparedStatement pst=null;
    */

    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
        setIcon();
       // conn=javaconnect.ConnectDB();
        Update_Payment();
    }
     public void setIcon()
    {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo-nonetext.png")));
    }
    public void Update_Payment()
    {
        Connection conn=null;
    ResultSet rs=null;
   PreparedStatement pst=null;
   conn=javaconnect.ConnectDB();
        try
        {
            String sql="select Patient_ID,First_Name,Last_Name,Rupees,Payment,Pay_Method from Appointment_table";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            py_table.setModel(DbUtils.resultSetToTableModel(rs));
           // rs=pst.executeQuery();

        }
         catch(SQLException e)
         {
             JOptionPane.showMessageDialog(null,e+"\nConnection Error\nplease check..");
         }
       finally
        {
            try
            {
              if(rs!=null)
              {
                  rs.close();
                  
              }
              if(pst!=null)
              {
                  pst.close();
              }
              if(conn!=null)
              {
                  conn.close();
              }
            }
            catch(SQLException ex)
            {
               JOptionPane.showMessageDialog(null, ex);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pd_patient_id = new javax.swing.JTextField();
        pd_first_name = new javax.swing.JTextField();
        pd_last_name = new javax.swing.JTextField();
        pd_rupees = new javax.swing.JTextField();
        pd_payment = new javax.swing.JTextField();
        pd_pay_method = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        py_table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Appointment Patient Payment");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 190, 170);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 102, 102));
        jButton4.setText("<< Back");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(1230, 30, 120, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Payment on Appoointment");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(190, 20, 700, 170);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hospital-Top-Slider-Image.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(170, 20, 1200, 170);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Payment Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 36), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Patient ID");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 142, 29));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("First Name");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 127, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Last Name");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 120, 29));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Rupees");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 142, 28));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Payment");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 117, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Pay Method");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 117, 30));

        pd_patient_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pd_patient_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pd_patient_idActionPerformed(evt);
            }
        });
        jPanel2.add(pd_patient_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 167, 29));

        pd_first_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(pd_first_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 167, 30));

        pd_last_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(pd_last_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 167, 29));

        pd_rupees.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(pd_rupees, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 167, 30));

        pd_payment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(pd_payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 167, 30));

        pd_pay_method.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(pd_pay_method, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 167, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("ADD");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 116, 41));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 102));
        jButton2.setText("DELETE");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 116, 41));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 102));
        jButton3.setText("CLEAR");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, 116, 41));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Payment Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 36), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(0, 102, 102));

        py_table.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        py_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        py_table.setRowHeight(30);
        py_table.setRowMargin(2);
        py_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                py_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(py_table);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Appoint_Table().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Connection conn=null;
    ResultSet rs=null;
   PreparedStatement pst=null;
   conn=javaconnect.ConnectDB();
        try
        {
            String a=pd_patient_id.getText();
            String b=pd_first_name.getText();
            String c=pd_last_name.getText();
            String d=pd_rupees.getText();
            String e=pd_payment.getText();
            String f=pd_pay_method.getText();
            if(a.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Patient ID is Empty");
            }
            else if(d.isEmpty())
                    {
                        JOptionPane.showMessageDialog(null, "Rupees is Empty");
                    }
            else
            {
                                                                                    
            String sql="update Appointment_table set First_Name='"+b+"',Last_Name='"+c+"', Rupees='"+d+"',Payment='"+e+"',Pay_Method='"+f+"' where Patient_ID='"+a+"'";
                    
             pst=conn.prepareStatement(sql);
             int C=JOptionPane.showConfirmDialog(null,"Do you want to Really Save?","Conform Save",JOptionPane.YES_NO_OPTION);
              if(C==0)
              {
                   pst.execute();
             JOptionPane.showMessageDialog(null,"Save");
             Update_Payment();
              pd_patient_id.setText("");
        pd_first_name.setText("");
        pd_last_name.setText("");
        pd_rupees.setText("");
        pd_payment.setText("");
        pd_pay_method.setText("");
              }
            }
            
                  
              
        }
        catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,e+"\nConnection Error\nplease check..");
        }
        
        finally
        {
            try
            {
              if(rs!=null)
              {
                  rs.close();
                  
              }
              if(pst!=null)
              {
                  pst.close();
              }
              if(conn!=null)
              {
                  conn.close();
              }
            }
            catch(SQLException ex)
            {
               JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void py_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_py_tableMouseClicked
        // TODO add your handling code here:
        Connection conn=null;
    ResultSet rs=null;
   PreparedStatement pst=null;
   conn=javaconnect.ConnectDB();
        try
        {
            int row=py_table.getSelectedRow();
            String Table_click=(py_table.getModel().getValueAt(row,0).toString());
            String sqll="select * from Appointment_table where Patient_ID='"+Table_click+"'";
            pst=conn.prepareStatement(sqll);
            rs=pst.executeQuery();
            if(rs.next())
            {
                String a=rs.getString("Patient_ID");
                pd_patient_id.setText(a);
                String b=rs.getString("First_Name");
                pd_first_name.setText(b);
                String c=rs.getString("Last_Name");
                pd_last_name.setText(c);
                String d=rs.getString("Rupees");
                pd_rupees.setText(d);
                String e=rs.getString("Payment");
                pd_payment.setText(e);
                String f=rs.getString("Pay_Method");
                pd_pay_method.setText(f);
            }
                    Update_Payment();

            
        }
        catch(SQLException e)
        {
             JOptionPane.showMessageDialog(null, e+"\nConnection Error\nplease check..");
        }
        finally
        {
            try
            {
              if(rs!=null)
              {
                  rs.close();
                  
              }
              if(pst!=null)
              {
                  pst.close();
              }
              if(conn!=null)
              {
                  conn.close();
              }
            }
            catch(SQLException ex)
            {
               JOptionPane.showMessageDialog(null, ex);
            }
        }
         
    }//GEN-LAST:event_py_tableMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        pd_patient_id.setText("");
        pd_first_name.setText("");
        pd_last_name.setText("");
        pd_rupees.setText("");
        pd_payment.setText("");
        pd_pay_method.setText("");

        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Connection conn=null;
    ResultSet rs=null;
   PreparedStatement pst=null;
   conn=javaconnect.ConnectDB();
        try
        {
            String a=pd_patient_id.getText();
            if(a.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Patient ID is Empty");
            }
            else
            {
            String sql="delete from Appointment_table where Patient_ID=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1,pd_patient_id.getText());
            int c=JOptionPane.showConfirmDialog(null,"Do you want to Relly Delete ?","Conform Delete",JOptionPane.YES_NO_OPTION);
            if(c==0)
            {
                pst.execute();
                JOptionPane.showMessageDialog(null,"Deleted");
                        Update_Payment();

            }
            }
                    
        }
        catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, e+"\nConnection Error\nplease check..");
        }
        finally
        {
            try
            {
              if(rs!=null)
              {
                  rs.close();
                  
              }
              if(pst!=null)
              {
                  pst.close();
              }
              if(conn!=null)
              {
                  conn.close();
              }
            }
            catch(SQLException ex)
            {
               JOptionPane.showMessageDialog(null, ex);
            }
        }
        pd_patient_id.setText("");
        pd_first_name.setText("");
        pd_last_name.setText("");
        pd_rupees.setText("");
        pd_payment.setText("");
        pd_pay_method.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void pd_patient_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pd_patient_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pd_patient_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
                //JOptionPane.showMessageDialog(null,"Select Data From Table First");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pd_first_name;
    private javax.swing.JTextField pd_last_name;
    private javax.swing.JTextField pd_patient_id;
    private javax.swing.JTextField pd_pay_method;
    private javax.swing.JTextField pd_payment;
    private javax.swing.JTextField pd_rupees;
    private javax.swing.JTable py_table;
    // End of variables declaration//GEN-END:variables
}
